### ISSUE TITLE
CI Windows is extremely slow at installing dependencies

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#105]
Perhaps I can look into moving to GitHub actions?

**Comment by s-weigand** [comment]
Feel free to hav a look at my CI-CD workflow ^^
https://github.com/s-weigand/flake8-nb/blob/ed1236d59a7a9163e7a23c46c08292b3497d2789/.github/workflows/test.yml#L137-L187

**Comment by MarcoGorelli** [comment]
closed in #134
