### ISSUE TITLE
TST check before vs after for all notebooks

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#122]

**Comment by MarcoGorelli** [comment]
only checking this for those where mutation is allowed

**Comment by vijayvkm7891987** [comment]
Hello Marco, What's this?

**Comment by MarcoGorelli** [comment]
Hello @vijayvkm7891987 ! What I meant here was that I should check whether notebooks changed after a command is applied to them. For example, if I apply `nbqa flake8 notebook.ipynb` I would not expect the notebook to change.

I opened this issue before I introduced the `--nbqa-mutation` flag though, so now it's not really necessary to check this.

Are you interested in contributing? If so, some help on supporting bash cells (#152) would be really appreciated - as would any kind of clean-up / performance improvement / documentation / etc.

**Comment by vijayvkm7891987** [comment]
Thank you. Actually,I am engaged in multiple tasks. But, I will look into
this.

Regards,
Vijay
