### ISSUE TITLE
use --treat-comment-as-code when running isort

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#163]
see https://github.com/timothycrosley/isort/issues/1338#issuecomment-666918626

**Comment by girip11** [comment]
I could not get whats this change about. Could you elaborate with an example?

**Comment by MarcoGorelli** [comment]
Sorry, this is probably from when I was still working on this on my own - I just meant to document `--treat-comment-as-code`. I'll rephrase now
