### ISSUE TITLE
ENH make it configurable which cells to skip

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#195]
ATM it's just bash and script, these could remain the default

**Comment by s-weigand** [comment]
We could [use celltags like I do in `flake8-nb`](https://flake8-nb.readthedocs.io/en/latest/usage.html#cell-tags)

**Comment by MarcoGorelli** [comment]
If I've understood, that'd involve adding `jupyterlab` as a dependency. At the moment this package is just written using the Python standard libraries, so I'm not 100% sure I'd want to add a dependency...will think about it

**Comment by s-weigand** [comment]
[Celltags](https://stackoverflow.com/a/48015303/3990615) are just some meta data added to the `"metadata"` property of a cell.
https://github.com/s-weigand/flake8-nb/blob/f9ebdee61989f77ee4c6786e4291b7be7a51f315/flake8_nb/parsers/cell_parsers.py#L73

There is no need to add `jupyterlab` as a dependecy of `nbQA`, I just meant that adding cell tags is now part of `jupyterlab` core and thus easy for users to add.
Before, you needed to write the proper metadata as json by hand or install an extension to `jupyterlab`, so it was less convenient for users.

**Comment by MarcoGorelli** [comment]
Ah, I see what you mean, thanks for explaining! Yes, that would be a possibility

**Comment by MarcoGorelli** [comment]
> We could [use celltags like I do in `flake8-nb`](https://flake8-nb.readthedocs.io/en/latest/usage.html#cell-tags), since `jupyterlab>=2` it is even part of the core lab, so no extension needed.

Revising this several months later, and I think that's what we should've done, sorry for having done `--nbqa-ignore-cells` instead

**Comment by MarcoGorelli** [comment]
For `black` you can wrap it with
```
# fmt: off
<code>
# fmt: on
```

**Comment by MarcoGorelli** [comment]
>  the only appropriate usage would be for educational material (tutorial/lecture/book)

Seems like they want it here https://github.com/ukgovdatascience/govcookiecutter/pull/31

I think we could have `--nbqa-skip-celltags` to which you pass the name of the celltag to ignore

**Comment by psychemedia** [comment]
"I think we could have --nbqa-skip-celltags to which you pass the name of the celltag to ignore"

Or for generality, one or more cell tags you want to exclude.

**Comment by MarcoGorelli** [comment]
you're right, thanks!

**Comment by psychemedia** [comment]
There's also the converse (not sure if that's already available?) eg along lines of `--nbqa-use-celltags` to opt one or more tags in for testing and exclude all others?

**Comment by MarcoGorelli** [comment]
true...I think, let's start with `--nbqa-skip-celltags`, then if someone has a use-case for `--nbqa-use-celltags` and open an issue for it we can add that.

I'll see if I can get this done on Friday

**Comment by MarcoGorelli** [comment]
@psychemedia as of 0.13.0, this should be available - would really appreciate it you could try this out and report any bugs, thanks :+1:

**Comment by psychemedia** [comment]
@MarcoGorelli Yep, seemed to work fine with a CLI command of the form:

`nbqa black nbqa-test.ipynb --nbqa-mutate --nbqa-skip-celltags=no,neither`

Thanks:-)
