### ISSUE TITLE
BUG pick up config file from project root

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#200]
Currently, if you run `nbqa isort` it'll only pick up a `.nbqa.ini` file if it's in the current working directory. It should be able to pick it from the project root, regardless of where `nbqa` is being run from

**Comment by s-weigand** [comment]
Just traverse up the path till you find a matching file.
It could look something like this:
```python
def get_config_path(config_file_name:str=".nbqa.ini"):
    current_path = Path(os.getcwd()).resolve()
    # recurse up until you are in the root dir
    while current_path != current_path.parent:
        config_file = current_path / config_file_name
        if config_file.is_file():
            return config_file
        current_path = current_path.parent
```

**Comment by MarcoGorelli** [comment]
Some care is needed though, because the config file specifies other config files (e.g. setup.cfg) relative to the repository root

**Comment by s-weigand** [comment]
Maybe the art student approach ("copy from the masters") would fit here.
Just having a peek how `flake8` and so on do it ^^

**Comment by MarcoGorelli** [comment]
Sure, thanks - I almost have a PR ready though ("inspired" by how `black` do it), so don't waste too much time on this :smile:
