### ISSUE TITLE
BUG? nbqa black removes trailing semi-colon

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#241]
e.g. after a plot

**Comment by MarcoGorelli** [comment]
see for an idea of how to do this https://github.com/dfm/black_nbconvert/blob/main/black_nbconvert.py

**Comment by girip11** [comment]
Could you add a sample code snippet here for better understanding

**Comment by MarcoGorelli** [comment]
Sure - see cell 1 from here https://docs.pymc.io/notebooks/GLM.html

```
scatter_matrix(trace_to_dataframe(trace_sat), figsize=(12,12));
```
This is common if you want to plot something but suppress the unnecessary matplotlib output

**Comment by girip11** [comment]
Thanks. Now I understand the bug better and your solution as well
