### ISSUE TITLE
indented magics don't work if they're meant to be indented

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#249]
e.g.

```python
if True:
    %time True
pass
```

This will get transformed to
```python
if True:
# commented out line
pass
```
which isn't valid syntax.

I'm tempted to say that the fix here would be to replace magics with
```
pass  # nbqamagic
```
and then, in the future, have a less hacky solution

**Comment by MarcoGorelli** [comment]
I think I'll try to fix this together with #248, serves me right for trying to use such a hack...

**Comment by MarcoGorelli** [comment]
This isn't the easiest thing...I'm tempted to disallow indented magics, unless they would otherwise be valid Python syntax.

So
```
if True:
    %time func()
```
would be allowed, but
```
    %%bash
```
wouldn't. I can't see why anyone would want to indent a magic unless it was to time a Python command

**Comment by girip11** [comment]
I agree with you that commenting out line magic(or cell magic) with `# NBQAMAGIC` seems like a hacky solution.

I have a proposal for handling line magic (with and without indentation). 

Line magic in ipython starts with `%`. Line magic statement can either be indented or not indented.

1. If the line magic statement is not indented, we have **no issue** in replacing the line magic with `pass ...`(basically your logic).
2. If the line magic statement is **indented**, then it could be either **intentional**(as part of python context) or **unintentional**. 
   a. If the indentation is intentional, then we have no issue.
       ```Python
       # This can be safely replaced with `pass ...`
       if True:
           %time func()
       ```
   b. This is where we have issue. Suggested solution
        * Check if the current line is a line magic or cell magic
        * If we get a line magic, replace the line magic(%x) with your replacement  code while preserving the indentation. For example `    %time func` is replaced as `     pass #nbqamagic`
        * Now take all the source code of the current notebook cell including the currently replaced line magic statement and pass this source code string to `ast.parse(source_code)` from the `ast` module. If we get an indentation error, then we know that's because of our replaced python statement `    pass #nbqamagic`
        * Now store this line number and the original line magic statement somewhere. We will need this when we need to modify the original notebook.

## WRONG     
![image](https://user-images.githubusercontent.com/5471162/94142562-1afebc80-fe8c-11ea-8116-08422c8dbad9.png)

## RIGHT
![image](https://user-images.githubusercontent.com/5471162/94142689-4f727880-fe8c-11ea-8909-5baa97a8fe07.png)

## Pros

* This approach does not use any external library.
* Handles all sorts of line magic.

**Comment by girip11** [comment]
Also I suggest replacing `%time func()` (in general any line magic) with `print("# LOC:<CELL_NUMBER>,<LINE NUMBER>")`.

We will have a dictionary, storing key = `tuple(cell_no, line_number)` and value = `original line magic statement without indentation`. After the tool (black, flake8) runs on the temp python file, we can iterate through this dictionary and straight away replace the `print("# LOC:<CELL_NUMBER>,<LINE NUMBER>")` with our dictionary value.

**Comment by girip11** [comment]
For cell magics, we currently comment out the entire cell and that will work anyways with or without indentation. But we can optimize by skipping the whole cell with a  cell magic not to be copied to the temp python source file

**Comment by MarcoGorelli** [comment]
I really like the idea of using `ast.parse`, definitely seems safer than just passing the file to the third-party tool and hoping for the bets, which is what my solution did :rofl: :flushed: 

Is there any advantage to using `print` over `pass`? e.g. would
```
pass # LOC:(1,2)
```
accomplish the same thing?

> Here we incur some extra computation(AST parsing for the cell source code only) every time we encounter an indented line magic.

IMO this is fine and justifiable

> But we can optimize by skipping the whole cell with a cell magic not to be copied to the temp python source file

:+1:

**Comment by girip11** [comment]
Using `print` is better than `pass` (futuristic purpose). A linter in the future might complain the `pass` statement in the below snippet to be a code smell (unnecessary no-op statement). But `print` would escape from the eyes of such linters 

```Python
pass  # ...
print("Hello")
```

**Comment by girip11** [comment]
I should give the credit to you. I got the `ast.parse` and `print` idea only when I looked at your proposal of using `pass` statement instead of `#NBQAmagic`

**Comment by MarcoGorelli** [comment]
> Using `print` is better than `pass` (futuristic purpose). A linter in the future might complain the `pass` statement in the below snippet to be a code smell (unnecessary no-op statement). But `print` would escape from the eyes of such linters
> 
> ```python
> pass  # ...
> print("Hello")
> ```
> 
> Refer to this issue [PyCQA/pylint#2208](https://github.com/PyCQA/pylint/issues/2208)

That's a really good point, thanks!! I hadn't thought of that! None of the tools which nbqa is meant to support should execute the Python file anyway, so I don't think the extra stdout would interfere.

I'll update #257 now to use `print` instead of `pass` - if it's OK, I'd keep the `ast.parse` for a separate PR as I think getting both changes in together will make the PR too big, and because I think (from trying to run this on many notebooks from Kaggle and from PyMC3) that unintentionally indented magics are quite rare.

> Here we are not calculating any checksum, also replacing back the line magic is simpler.

My motivation for using a checksum is that the chances of someone having a random hash in their code is really low, so we don't risk accidentally replacing the wrong thing.

**Comment by girip11** [comment]
Sure. I will review the PR. As you rightly pointed out `ast` can be taken as enhancement to the current PR.

**Comment by MarcoGorelli** [comment]
Just tried using `print`, but then it messes with the output from running `nbqa doctest`...any other ideas? All I can think of now is
```
pass  # pylint: disable=W0107
```
?

**Comment by girip11** [comment]
> If I've understood, your ideas is to use `# LOC:(1,2)` and then, in `replace_source`, replace such a comment with e.g. the second line from the first cell. I think it works, just not entirely convinced it would be simpler than holding a dict with {temporary_line: original_line} in memory.

My point

**Comment by girip11** [comment]
> Just tried using `print`, but then it messes with the output from running `nbqa doctest`...any other ideas?

Could you elaborate on this? I didn't get how it is affecting doctest.

**Comment by MarcoGorelli** [comment]
Sure - if I use the replacement
```
print('I love Python')  # nbqa<hash>
```
and then run
```
python -m nbqa doctest tests/data/notebook_for_testing_copy.ipynb
```
, then here's the output:
```python
I love Python
I love Python
**********************************************************************
File "/home/marco/nbQA-dev/tests/data/notebook_for_testing_copy.ipynb", cell_2:8, in notebook_for_testing_copy   .hello
Failed example:
    hello()
Expected:
    'hello world\n'
Got:
    I love Python
    'hello world\n'
**********************************************************************
File "/home/marco/nbQA-dev/tests/data/notebook_for_testing_copy.ipynb", cell_2:10, in notebook_for_testing_copy   .hello
Failed example:
    hello("goodbye")
Expected:
    'hello goodby'
Got:
    I love Python
    'hello goodbye'
**********************************************************************
1 items had failures:
   2 of   2 in notebook_for_testing_copy   .hello
***Test Failed*** 2 failures.
```

**Comment by girip11** [comment]
> If I've understood, your ideas is to use `# LOC:(1,2)` and then, in `replace_source`, replace such a comment with e.g. the second line from the first cell. I think it works, just not entirely convinced it would be simpler than holding a dict with {temporary_line: original_line} in memory.

Actually I was suggesting  `# LOC:(1,2)` to be used as in `print("# LOC:(1,2)")`, and instead of maintaining mapping like 

```Python
{
 "print("#LOC:(1,2)")": "%test func()"
}
```

I was thinking 

```Python
{
 (1,2): "%test func()"
}
```

would be memory efficient since we can use a template string for  `print(# LOC: (1,2))`.

**Comment by MarcoGorelli** [comment]
Would the memory saving be noticeable in going from `'print("#LOC:(1,2)")'` to `(1,2)`? I have a feeling I've misunderstood, if you feel like opening a draft PR to explain perhaps that's easiest?

Also, `print("#LOC:(1,2)")` would still result in `"#LOC:(1,2)"` appearing in the output of `doctest` if, as in `notebook_for_testing_copy.ipynb`, there is a magic inside the function.

It'd be great if there was a way of removing magics entirely and then putting them back in at the end, I just can't think of how. Replacing them with something, whether a comment, `pass`, or `print`, will have pros and cons

**Comment by girip11** [comment]
> Would the memory saving be noticeable in going from 'print("#LOC:(1,2)")' to (1,2)? I have a feeling I've misunderstood, if you feel like opening a draft PR to explain perhaps that's easiest?

You are right. It's just a usual minor optimization. There won't be a significant difference in memory saving.

> Also, print("#LOC:(1,2)") would still result in "#LOC:(1,2)" appearing in the output of doctest if, as in notebook_for_testing_copy.ipynb, there is a magic inside the function.

Now I understood the `doctest` issue. 

> It'd be great if there was a way of removing magics entirely and then putting them back in at the end, I just can't think of how. Replacing them with something, whether a comment, pass, or print, will have pros and cons

I too wanted such an approach. But could not find a better way yet.

**Comment by girip11** [comment]
Or we could just use `pass` now as it is in the PR. Enhancement can come later, since current solution works except very rare indented line magic scenario.

**Comment by girip11** [comment]
A hacky but extensible solution would be to use `pass` for non linters(default) and `print` for linters(can be configured in for supported linters).

**Comment by MarcoGorelli** [comment]
Yes! Now that's a great idea!

**Comment by girip11** [comment]
But these different string templates should follow some format.

Ex: 
 `pass # LOC:($cell, $line)` and `print(# LOC($cell, $line))`. In our code, we will replace the template with the values of `$cell` and `$line`.

In this case, you could very well implement your own hash logic too. I am fine with any logic you would decide on.
Ex: 
 `pass # $hash` and `print("$hash")`. In our code, we will replace the template with the values of `$hash.

**Comment by s-weigand** [comment]
Why not just use `nbconvert`, since [it is part of notebook](https://github.com/jupyter/notebook/blob/09ba565c96619d2150448bb0f4392004decc1014/setup.py#L112) anyway?
At least that is how I handle magic-commands in `flake8-nb`
https://github.com/s-weigand/flake8-nb/blob/2acdbf2b59ca230c5d77fd17cc192d9c5f79f567/flake8_nb/parsers/notebook_parsers.py#L85-L104

**Comment by girip11** [comment]
> Why not just use `nbconvert`, since [it is part of notebook](https://github.com/jupyter/notebook/blob/09ba565c96619d2150448bb0f4392004decc1014/setup.py#L112) anyway?

@s-weigand  I looked at your approach. You use `nbconvert.filters.ipython2python` to convert ipython syntax to python code.

```Python
# below call returns "get_ipython().run_line_magic('time', 'func()')\n"
ipython2python("%time func()")

# Below call returns "get_ipython().run_cell_magic('time', 'func()', '')\n"
ipython2python("%%time func()")
```

Later you check if the source line startswith `get_ipython`, if yes then you add an additional [ipython import](https://github.com/s-weigand/flake8-nb/blob/2acdbf2b59ca230c5d77fd17cc192d9c5f79f567/flake8_nb/parsers/notebook_parsers.py#L257) ` intermediate_code = "from IPython import get_ipython\n\n\n"`.  I like this approach, but I have the following concerns

1. With respect to running **isort**. In your case flake8 is a linter, does not mutate the source notebook. So this approach is fine. When nbqa runs `isort` on the notebook, adding the import statement could always cause isort to complain. To suppress we might have to use `from IPython import get_ipython #isort:skip`. Do you see any other way of dealing with this?

2. In your case how are indented line magics handled? For instance,

```Python
# I wrote code as below
if True:
   %time func()

# Later I decided to to this code, but i fail to remove the indentation. After all I rely on tools to fix indentation.
     %time func()
```
![image](https://user-images.githubusercontent.com/5471162/94225968-0960f780-ff14-11ea-8830-e552b743b67b.png)


With nbqa's approach, we have to opportunity to even fix the line magic indentation. Also I don't see a big difference in the way we handle line magic in `flake8-nb`. Optionally to get the best of both the world's, I suggest I would use `ipython2python` to detect if the current line is a cell or line magic and apply nbqa's logic accordingly. What are your thoughts?

**Comment by s-weigand** [comment]
Before this issue I didn't even know that you could indent magic commands 😅 
In my case the `"from IPython import get_ipython\n\n\n` is added to prevent a `NameError`, when `flake8` parses the file (this mostlikely will also be an issue with `black`, since it only works on valid python code).

```python
NameError: name 'get_ipython' is not defined
```

ATM I only see a problem with `isort`,  where you already provided the solution with `#isort:skip`.

Ofc for tools which mutate the code, the import needs to be removed again and the `get_ipython().run_...` needs to be replaced with the magic command (in magic syntax) before writing back to the file. But I guess this can be done fairly easy with Regex.

As for indentation, `ipython2python` works fine with that when you use it on a cell rather than a line (I will need to change this in `flake8-nb` as well).
The problem here might be with `black` if the command gets too long, i.e. a bash script.
Also black won't like the single quotes.

```python
In [1]: from nbconvert.filters import ipython2python

In [2]: ipython2python("    %time func()")
Out[2]: "get_ipython().run_line_magic('time', 'func()')\n"

In [3]: ipython2python("if True:\n    %time func()")
Out[3]: "if True:\n    get_ipython().run_line_magic('time', 'func()')\n"

In [4]: ipython2python("%%bash\nls -la\ncat file_name")
Out[4]: "get_ipython().run_cell_magic('bash', '', 'ls -la\\ncat file_name')\n"
```

**Comment by MarcoGorelli** [comment]
> Why not just use nbconvert, since it is part of notebook anyway?

Thanks - yes, I did think of that, but the handling of magics was the bottleneck for me
