### ISSUE TITLE
QUESTION: how do you measure theoritical performance/time taken by a cell or whole notebook?

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#259]
Another one I'm raising this just to discuss if there is a way to measure the `O(..)` of a block of code or blocks of code in the notebook?

This falls under the Theory of Computing concepts (Big O and little O) but there is practical use for it. I use performance measuring tools but that would be after the fact. But if something can already trigger/alert just before you are going to run a cell, or when analysing a cell it would be helpful to the user. See this blog if it helps: https://stackabuse.com/big-o-notation-and-algorithm-analysis-with-python-examples/

In case your other analysis already covers this then please close this. Otherwise, it would be a helpful feature to have.

Maybe related to #258

**Comment by neomatrix369** [comment]
Btw the reason I raised this question, I was inquiring to see if this would/could be a part of the QA checks already performed by nbQA!

**Comment by MarcoGorelli** [comment]
Thanks @neomatrix369 for the question!

If there's a Python tool which already measures this (I don't think there is), then we can look at supporting it for Jupyter Notebooks - do you know if one exists?

**Comment by MarcoGorelli** [comment]
Closing as I'm pretty sure this isn't possible, but thanks for the suggestion!
