### ISSUE TITLE
BUG? `black` splits comment after trailing comma, nbqa doesn't preserve trailing comma

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#282]
Not sure whether to consider this a bug or whether to list it as a known limitation
```python
plt.plot();  # some comment
```
`nbqa black` would transform this as
```
plt.plot()
# some comment
```

@girip11 thoughts?

**Comment by girip11** [comment]
Right now let's treat this as a **known limitation**, since we have a simple workaround in this case. The workaround is to place the comment above the line. If that's the case, then you have already coded up the logic of handling/preserving semicolon present in the last line of a cell.

**Comment by girip11** [comment]
@MarcoGorelli  We can close this as we can do nothing about it.

**Comment by MarcoGorelli** [comment]
Let's repurpose this as a documentation tasks, we can add a 'known limitations' page somewhere
