### ISSUE TITLE
Q: Can nbQA be used for quality checks inside a running notebook?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [nbQA-dev/nbQA#289]
I am new here and trying to understand how things work. I played with some of the command line options and am now wondering  whether any of the nbQA-supported QA mechanisms could be employed while running a notebook, rather than after the fact.

For instance, if I were to type into a code cell, is there a mechanism to have black, isort etc. review that code and propose relevant changes, ideally before I run the cell?

**Comment by MarcoGorelli** [comment]
Hi @Daniel-Mietchen - thanks for your question!

If you use JupyterLab, you could use https://github.com/ryantam626/jupyterlab_code_formatter to format your code cells for you while you're running your notebook. I think there's some other similar projects out there too.

This tool, on the other hand, is (currently) only intended to be run from the command-line - my original use-case was that I wanted to run some code-quality checks during continuous integration and wanted to make sure that any notebook I checked in to my repository met certain criteria

**Comment by MarcoGorelli** [comment]
Having said that, I think we could add a `--nbqa-diff` flag which would show you which changes a tool would make to your notebook _without actually applying them_.

Thanks for the idea, I think we should implement this!

**Comment by MarcoGorelli** [comment]
@all-contributors please add @Daniel-Mietchen for ideas

**Comment by m3h0w** [comment]
Just wanted to drop a comment here saying that I've been struggling to find a good and easy-to-use tool that could trigger formatting from within the notebooks and it seems like an obvious and (hopefully) not so difficult upgrade to nbQA :)

**Comment by MarcoGorelli** [comment]
Hi @m3h0w 

Something I just tried was to add a cell with
```python
!nbqa black --nbqa-mutate
```
and it seemed to work! You'll have to reload the window though. Would this work for you?

An alternative would be to make a jupyter extension https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html , although I don't use jupyter notebooks myself (I just edit them from within vscode) so this won't be very high priority on my to-do list (though if anyone wanted to submit a pull request for that, or to make a separate package to that, I'd love to see it!)

**Comment by MarcoGorelli** [comment]
Hi,

I've just tried this out again, and it turns out that if you run e.g.
```
nbqa pyupgrade notebook.ipynb --py37-plus
```
from the command line while your notebook is running, and then refresh the page, then your notebook will have been reformatted in place _and_ the state will have been preserved.

For example, if you have a (running) notebook with
```python
# cell 1
import pandas as pd

# cell 2
df = pd.DataFrame({'a': [1,2,3]})

# cell 3
df
```

and you run all the cells and then run

```
nbqa black notebook.ipynb --nbqa-mutate
```
from the command line and then refresh, then your notebook will look like
```
# cell 1
import pandas as pd

# cell 2
df = pd.DataFrame({"a": [1, 2, 3]})

# cell 3
df
```

If you then execute _just_ cell 3, and you will see
```console
  | a
-- | --
1
2
3
```

So, it looks like nbqa works on running notebooks _and_ preserves their state.

@m3h0w @Daniel-Mietchen does this work for your use cases? Are we OK to close this issue? I've opened up a separate one to keep track of adding `--nbqa-diff`

Thanks :smile:

**Comment by Daniel-Mietchen** [comment]
@MarcoGorelli Thanks &mdash; this worked fine, and looking forward to testing the --nbqa-diff flag too. On the way, I noticed another bug, for which I opened another ticket.
