### ISSUE TITLE
Running nbqa with flake8 complains about blank lines on notebook cells with functions

### ISSUE THREAD

**Issue by girip11** [nbQA-dev/nbQA#293]
Consider a cell containing a function

```Python
# cell contents
def get_dataset():
    return make_classification(
        n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=7
    )
```

I am getting the warnings 

* `E302 expected 2 blank lines, found 1`.
* `E305 expected 2 blank lines after class or function definition, found 1`

**Comment by MarcoGorelli** [comment]
I'm not sure how we could consistently put the correct number of blank lines between cells...I'm tempted to just have a "suggested configs" document in which we suggest which errors to ignore for which tools. Or do you think this is solvable?

**Comment by girip11** [comment]
I was about to type exactly the same "suggested configs".

**Comment by girip11** [comment]
Is there any issue appending 2 spaces after each cell content in the temp python file and removing those spaces when writing back to the source notebook?

**Comment by MarcoGorelli** [comment]
I _think_ there was some issue with isort from doing that...would that solve the problem?

**Comment by girip11** [comment]
Adding two new lines seems to solve the problem. I tested the following code with `isort`

## Before
```Python
#%%
import numpy as np
import pymc3 as pm
import arviz as az


#%%
from matplotlib import pyplot as plt
from scipy.special import betaln
from scipy.stats import beta
```


## After

```Python
#%%
import arviz as az
import numpy as np
import pymc3 as pm

#%%
from matplotlib import pyplot as plt
from scipy.special import betaln
from scipy.stats import beta

```

`isort` removes a newilne when it sorts the imports. But this wouldnt be an issue if we are splitting by just `#%%`. After the split, we can strip `\n` from the cell contents. I think this should work.

**Comment by MarcoGorelli** [comment]
> After the split, we can strip \n from the cell content

yes but if `isort` makes any changes, then won't it (potentially) return the wrong exit code? e.g. like this it could happen that you run `nbqa isort notebook.ipynb` and you get
```
fixing notebook.ipynb
```
but then if you do `git diff` you see that nothing has changed

**Comment by girip11** [comment]
> > After the split, we can strip \n from the cell content
> 
> yes but if `isort` makes any changes, then won't it (potentially) return the wrong exit code? e.g. like this it could happen that you run `nbqa isort notebook.ipynb` and you get
> 
> ```
> fixing notebook.ipynb
> ```
> 
> but then if you do `git diff` you see that nothing has changed

Great point. I didn't think isort would change the file when no imports has to be sorted.
