### ISSUE TITLE
Command 'black' not found while running 'black' without nbqa works fine

### ISSUE THREAD

**Issue by m3h0w** [nbQA-dev/nbQA#318]
When running `nbqa black '<notebook_name>.ipynb'` I get the following error:

> Traceback (most recent call last):
>   File "/home/mikey/.local/bin/nbqa", line 8, in <module>
>     sys.exit(main())
>   File "/home/mikey/.local/lib/python3.6/site-packages/nbqa/__main__.py", line 502, in main
>     for i in cli_args.root_dirs
>   File "/home/mikey/.local/lib/python3.6/site-packages/nbqa/__main__.py", line 502, in <listcomp>
>     for i in cli_args.root_dirs
>   File "/home/mikey/.local/lib/python3.6/site-packages/nbqa/__main__.py", line 446, in _run_on_one_root_dir
>     _get_arg(root_dir, tmpdirname, nb_to_py_mapping, project_root),
>   File "/home/mikey/.local/lib/python3.6/site-packages/nbqa/__main__.py", line 360, in _run_command
>     f"Command `{command}` not found. "
> ValueError: Command `black` not found. Please make sure you have it installed before running nbqa on it.

While if I just run `black <filename>.py` it works fine.

**Comment by MarcoGorelli** [comment]
Hi @m3h0w 

Massive thanks for your report!

A couple of questions:

- which version of nbqa are you using? You can see this by typing `nbqa --version`
- if you do `python -m black <filename>.py`, does it work?

**Comment by girip11** [comment]
From the exception trace shared, I can deduce nbqa version to be `3.0.0`. 

From your exception trace, I can see nbqa is found at `/home/mikey/.local/lib/python3.6/site-packages/nbqa/` (package is found under the user's home directory `.local` dir). 

As @MarcoGorelli  pointed, they might be pointing to different places.

**Comment by MarcoGorelli** [comment]
Sounds like a good suggestion...I'm all in for making this as user-friendly as possible

**Comment by girip11** [comment]
How about adding this to the issues? I can take up this work item.

**Comment by MarcoGorelli** [comment]
Go ahead, thanks! :+1:

**Comment by m3h0w** [comment]
`nbqa --version` -> `0.3.0`

And I can't run `python -m black` successfully because my `python` command is running python2.7, while I installed black using `python3 -m pip install black` under python3.6. I guess that's the problem then? That nbqa runs `python` command?

**Comment by MarcoGorelli** [comment]
@m3h0w ah, I see - yes, that is indeed the issue!

I think the simplest fix here would be to use `python3` internally, rather than assuming everyone is working in a virtual environment in which `python` points to `python3`.

Having said that, I do recommend using a virtual environment instead :smile: https://realpython.com/python-virtual-environments-a-primer/

**Comment by MarcoGorelli** [comment]
@all-contributors please add @m3h0w for bug report

**Comment by s-weigand** [comment]
+1 for `sys.executable`

The other option would be to not to use `python -m`:
https://github.com/nbQA-dev/nbQA/blob/02d3b3702ab1752efbd05cb047d887159a0b4683/nbqa/__main__.py#L344

And use `shell=True` instead. That way `nbqa` could support tools which aren't runnable as a module (i.e. only cli entry point defined and no `__main__.py`)

**Comment by MarcoGorelli** [comment]
> +1 for `sys.executable`

Cool, have opened #325 for that

> The other option would be to not to use `python -m`:

We could _just_ run `command`, but then `nbqa doctest` would no longer work, and that's something I'm quite keen on keeping.

> And use `shell=True` instead. That way `nbqa` could support tools which aren't runnable as a module (i.e. only cli entry point defined and no `__main__.py`)

My (albeit limited) understanding is that there may be security considerations for that https://docs.python.org/3/library/subprocess.html#security-considerations

Do you have an example of a tool which would require this?

**Comment by s-weigand** [comment]
IMHO the security concerns are more for applications like a webservices. 
If you have access to the shell already, there is no need to use shell injections.

And I have no example for a tool that would require this, just a suggestion.

**Comment by MarcoGorelli** [comment]
@m3h0w if you upgrade to version 0.3.1, then I'd like to this this should work

**Comment by m3h0w** [comment]
Works <3

Thanks for such a heartwarming and timely response 🥇 And for making this tool :)
