### ISSUE TITLE
[Question] Why are dependencies not cached in GitHub actions?

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#320]
This is not library-specific but would it not speed up the builds given 4 x 3 instances are run at a time, if we used the caching feature provided by GitHub actions, see [docs](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows).

I'm currently using this [cache action](https://github.com/actions/cache), see [my implementation](https://github.com/neomatrix369/nlp_profiler/blob/7e4ca8756bfd73d0b7f805d3c19e536bf0d7e266/.github/workflows/new-or-updated-changes.yml) - maybe you might want to use the ideas here (just a suggestion).

**Comment by neomatrix369** [comment]
As I have just gained some experience there,  I can certainly do it and see if it stands to my changes ;)

**Comment by neomatrix369** [comment]
I have created Project for this repo and also randomly sorted all the open issues under Backlog (long term) and To do (near term), but I'll leave it to you all to decide where they correctly belong.

**Comment by MarcoGorelli** [comment]
Wow, nice, thank you so much!
