### ISSUE TITLE
Provision for user to troubleshoot `Command not found.` error

### ISSUE THREAD

**Issue by girip11** [nbQA-dev/nbQA#321]
Currently, if nbqa and the QA tool to run are installed in different python environments, we would get `ValueError: Command black not found. Please make sure you have it installed before running nbqa on it.`

This feature adds a provision in nbqa to dump the path of the tool that will be run by nbqa using a command `which` or a flag `--which`. This can be print user friendly message if the tool cannot be found by nbqa. 

It could be something like 
* `nbqa which black` - This will introduce a new command.

This would make the user to better troubleshoot this issue and we can document how to handle this scenario in nbqa's documentation, thus making the user solve such issues on their own.

**Comment by MarcoGorelli** [comment]
Yes, that's probably better...if a user gets `command not found`, I think they'll likely give up on using this library if they can't find a solution before too long, so collecting all the necessary information for debugging right away is probably best

**Comment by s-weigand** [comment]
With #325 it is required that the tool is installed in the same env as `nbqa`.
So the check if the tool is installed can be done with `from importlib.util import find_spec`.

**Comment by s-weigand** [comment]
Also `nbqa` could list the installed and supported tools with the `--version` flag as `flake8` does.
```
$ flake8 --version
3.8.3 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.7.8 on Windows
```

**Comment by girip11** [comment]
This is the approach I am thinking of

* Introduce an option `nbqa black --find` to display black location, version etc as found by nbqa. I can use `importutil`, `imp`, `pkg_resources` modules. This is the success scenario where nbqa is able to find the tool.

* If nbqa can't find black, then we will display appropriate diagnostic message like what is nbqa installation path, and the used python executable path, then asking users to either install `pip(from same location as sys.executable) install black` or point to setting up python virtual environment. If case where user can't resolve this issue, then we can display a message to file bug/issue at nbqa github repo.

* When the user runs `nbqa black abc.ipynb --nbqa-mutate`, if the nbqa raises `ValueError("Command not found")` in that exception message in addition to what we display today, we will also ask the user to run `nbqa black --find` to troubleshoot this issue.

This one can be done with minimal changes and it will serve the purpose I think. Please reply if you have any queries.

**Comment by s-weigand** [comment]
Instead of looking for `ValueError("Command not found")` with speciffic message, a custom error (e.g. `NbqaMissingCommandError`) might be a cleaner approach.

**Comment by MarcoGorelli** [comment]
Nice! In general I'm hesitant to add extra methods to the public API, but this seems like a really well-thought out use-case, so I'm +1 on it

**Comment by girip11** [comment]
Thanks both for reviewing. I will start the implementation.

**Comment by girip11** [comment]
Closing this issue since PR #356 tries to address this by adding more information to the exception.
