### ISSUE TITLE
Add CLI flag to list supported tools

### ISSUE THREAD

**Issue by s-weigand** [nbQA-dev/nbQA#326]
IMHO it would be a good idea to only allow officially supported tools by default.
Additionally needed flags:
- `--list-supported` : print list of supported tools with short description
- `--experimental`: run a tool that isn't supported officially

As convenience flag, it would also be nice for users, to install supported tools with a flag, e.g.:
```
nbqa black <path> --install-missing
```
Guess for that feature `pip` would need to be a requirement of `nbqa`.

**Comment by MarcoGorelli** [comment]
these are what appear in the README and docs, so closing for now
