### ISSUE TITLE
Release nbqa via conda-forge

### ISSUE THREAD

**Issue by s-weigand** [nbQA-dev/nbQA#343]
If you want to add `nbqa` on `conda-forge` I can make a PR for that.

**Comment by MarcoGorelli** [comment]
That would be awesome, thank you!

**Comment by s-weigand** [comment]
I opened a [PR at conda-forge](https://github.com/conda-forge/staged-recipes/pull/12923)

**Comment by s-weigand** [comment]
Since the PR got merged and we have 3 releases on conda-forge, I will close this issue.
If you want to add a badge, here is the md code for that ^^
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/nbqa.svg)](https://anaconda.org/conda-forge/nbqa)
```markdown
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/nbqa.svg)](https://anaconda.org/conda-forge/nbqa)
```
