### ISSUE TITLE
Gitter for nbqa

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#344]
Is creating a [gitter.im](https://gitter.im/) room for nbqa an idea?

The team and the rest of the community users can hang around and throw ideas, less discussion on issue pages and more interaction - what do you think?

I'm already thinking of having one for my library

**Comment by MarcoGorelli** [comment]
Big enthusiastic +1 from me!

**Comment by MarcoGorelli** [comment]
@girip11 I wasn't able to add you manually, but here's the room if you want to join https://gitter.im/nbQA/nbQA

**Comment by girip11** [comment]
@MarcoGorelli I joined.
