### ISSUE TITLE
[Question/Discussion] Deadlinks checker in documents across the repo/library

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#345]
Just like I have this issue on https://github.com/neomatrix369/awesome-ai-ml-dl/issues/54, I have found a way to manually check for deadlinks in all of my markdown files in a repo.

I think there should be something that looks for such links in .rst and other document files as well.

When we find out, it would be good to add it to the `pre-commit` CI/CD GH action.

Can also be added to the local pre-commit.

In both cases it should be run when files that may contain hyperlinks are being committed

**Comment by s-weigand** [comment]
Why not just use `python -m sphinx . _build -b linkcheck`/`make linkcheck` inside the `docs` dir?

**Comment by MarcoGorelli** [comment]
Great idea!

> When we find out, it would be good to add it to the pre-commit CI/CD GH action.

> Can also be added to the local pre-commit.

Anything that runs as a local pre-commit hook also runs in the GH pre-commit action.

> Why not just use python -m sphinx . _build -b linkcheck/make linkcheck inside the docs dir

Nice! I think that would make for a great local pre-commit hook (so that feedback is faster than if you wait for the CI jobs)

**Comment by s-weigand** [comment]
IMHO having it as tox tests (e.g. `tox -e docs` and `tox -e links`) would make more sense, since the docs aren't changed that often and the tests take quite some time. I don't think anyone would want to wait 20sec per commit.

**Comment by MarcoGorelli** [comment]
I didn't realise it took that long - sure, that makes sense then!

**Comment by neomatrix369** [comment]
Looks like you guys have actioned this suggestion already - super cool!

**Comment by MarcoGorelli** [comment]
> Looks like you guys have actioned this suggestion already

Are you sure? I didn't think we had :rofl:

**Comment by neomatrix369** [comment]
> > Looks like you guys have actioned this suggestion already
> 
> Are you sure? I didn't think we had 🤣

Oh! Really! You haven't :P  ! Few  ideas were thrown, in the conversations above - not worth pursuing? I was suggesting for the .md files and not just the docs generated. 

But maybe it's not useful or applicable.

**Comment by MarcoGorelli** [comment]
Yes, I think it's useful (thanks for the suggestion!), we just haven't got round to doing it yet

**Comment by neomatrix369** [comment]
> Yes, I think it's useful (thanks for the suggestion!), we just haven't got round to doing it yet

I'll give it a whirl, leave it to me, and if don;t then just beat me to it! ;)

**Comment by s-weigand** [comment]
@neomatrix369 the link check should be allowed to fail on CI, since servers might be temporarily down (e.g. codecov times out quite often).
