### ISSUE TITLE
add --nbqa-diff flag

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#352]
Display diff _without_ applying it

**Comment by Daniel-Mietchen** [comment]
I think this would be really helpful to teach/ learn coding standards and for reviewing notebooks.

**Comment by MarcoGorelli** [comment]
Agreed! It's just a matter of finding the time to do it 😆 

If you're interested in submitting a pull request, that'd be hugely welcome - else we'll get round to it when we get a chance to

**Comment by Daniel-Mietchen** [comment]
@MarcoGorelli I had another look at this and liked what I saw &mdash; thanks. The only issue I noticed so far is that removal of trailing whitespace is not highlighted, which renders outputs like this a bit confusing
<img width="528" alt="Screen Shot 2020-11-22 at 18 42 02" src="https://user-images.githubusercontent.com/465923/99922104-9e0d8900-2cfc-11eb-83be-e7ee0d1b746a.png">

Some more notes [here](https://public.paws.wmcloud.org/12410844/100days/100days-Day-063.ipynb).

**Comment by Daniel-Mietchen** [comment]
Another oddity:
<img width="469" alt="Screen Shot 2020-11-22 at 20 11 38" src="https://user-images.githubusercontent.com/465923/99922654-b03cf680-2cff-11eb-86ff-8fb01240e0ec.png">

**Comment by MarcoGorelli** [comment]
Thanks @Daniel-Mietchen , really appreciate the report!

It would be good to highlight whitespaces, I agree, just need to figure out how.

Regarding the `cell 11` oddity - at the bottom it says
```
RuntimeError: Error reconstructing 100days-Day-063.ipynb
Please report a bug at https://github.com/nbQA-dev/nbQA/issues 
```
I'll have a look at that notebook - that you so much for helping us improve this package!

**Comment by MarcoGorelli** [comment]
Hi @Daniel-Mietchen 

With regards to `RuntimeError: Error reconstructing 100days-Day-063.ipynb` - I think it's because it contains the invalid syntax
```
nbqa black 100days-Day-062.ipynb --nbqa-diff
```
in cell 7.

We'll work on the error reporting anyway

**Comment by MarcoGorelli** [comment]
I couldn't reproduce this - I tried downloading the notebook and running the cell
```
!nbqa black *.ipynb --nbqa-diff
```
but got no output from it :thinking:

**Comment by MarcoGorelli** [comment]
TBH I'm surprised that `nbqa black *.ipynb` worked for you at all - the positional argument isn't meant to be a glob pattern, but rather a notebook or directory.

I would instead just run `nbqa black . --nbqa-diff` (by default, it'll only run on `.ipynb` files anyway)

@nbQA-dev/nbqa-core anyone have any idea how to reproduce this? I downloaded the notebook as
```
wget https://public.paws.wmcloud.org/12410844/100days/100days-Day-063.ipynb?format=raw
mv 100days-Day-063.ipynb?format=raw 100days-Day-063.ipynb
```
, then opened it and ran up to cell 11 (in a new virtual environment). But cell 11 gave me no output.

@Daniel-Mietchen perhaps if you could show the output of `!ls`, it would help?

**Comment by Daniel-Mietchen** [comment]
@MarcoGorelli [Here](https://public.paws.wmcloud.org/12410844/100days/100days-Day-094-nbqa-ls.txt) is a sample output of ```!ls``` from today, which should still have all the files that were there back then on Day 63.
