### ISSUE TITLE
ENH try parsing code after cell magic, ignore if can't

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#355]
I haven't (yet) got to the root of the issue, but the notebook in question is  

https://github.com/microsoft/computervision-recipes/blob/1bb489af757fde7c773e16fab87b24305cff4457/scenarios/detection/20_deployment_on_kubernetes.ipynb

----

I get

```console
$ nbqa black scenarios/detection/20_deployment_on_kubernetes.ipynb
error: cannot format scenarios/detection/20_deployment_on_kubernetes.ipynb: Cannot parse: 50:1: [print(f) for f in Path(data_path()/"odFridgeObjects"/"models").glob('**/*')]
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Comment by s-weigand** [comment]
For cases like this a `--keep-parsed-notebooks` flag is usefull (kinda related to #321)

**Comment by MarcoGorelli** [comment]
Yes, that'd be good!

Even with that, I can't tell what the problem is:
```python
# %%
import sys
sys.path.append("../../")

import os
from PIL import Image
from pathlib import Path
import requests
import json
import inspect

from utils_cv.common.image import ims2strlist
from utils_cv.common.data import data_path
from utils_cv.detection.model import DetectionLearner, get_pretrained_fasterrcnn
from utils_cv.detection.dataset import DetectionDataset
from utils_cv.detection.plot import (
    display_bboxes,
    PlotSettings,
    DetectionBbox
)
from utils_cv.common.azureml import get_or_create_workspace

from azureml.core.webservice import AksWebservice
from azureml.core.compute import AksCompute, ComputeTarget
from azureml.core.model import Model, InferenceConfig


# %%
type(0xDD9F885E)  # %reload_ex 0xDD9F885E
type(0xA4B2F1E3)  # %autoreloa 0xA4B2F1E3
type(0xA34775A)  # %matplotli 0xA34775A


# %%
# Azure resources
subscription_id = "YOUR_SUBSCRIPTION_ID"
resource_group = "YOUR_RESOURCE_GROUP_NAME"  
workspace_name = "YOUR_WORKSPACE_NAME"  
workspace_region = "YOUR_WORKSPACE_REGION"

# Choose a size for our cluster and the maximum number of nodes
VM_SIZE = "STANDARD_NC6" #STANDARD_NC6S_V3"
NODES = 3
KUBERNETES_CLUSTER_NAME = "od-aks-cluster"
DEPLOYMENT_SERVICE_NAME = "drink-detector"
MODEL_NAME = "drink-detector"


# %%
[print(f) for f in Path(data_path()/"odFridgeObjects"/"models").glob('**/*')]


# %%
detector = DetectionLearner.from_saved_model(name="my_drink_detector", path=data_path()/"odFridgeObjects"/"models")
```

**Comment by MarcoGorelli** [comment]
nevermind, not a bug, we just need to ignore the cell '%%writefile'

**Comment by girip11** [comment]
@MarcoGorelli : why not ignore all the cell magics(%%) by default? I mean the entire cell.

**Comment by MarcoGorelli** [comment]
We could do, but then there are cases when cells with cell magics contain valid code, e.g. `%%time`. Maybe we could do something similar to your idea of what to do with inline magics - check if what follows is valid Python code, and if it is, keep it, else ignore it?

**Comment by girip11** [comment]
How about checking if the cell magic contains python code (use ast.parse and look for Syntax error) and include it otherwise ignore those cells

**Comment by girip11** [comment]
> We could do, but then there are cases when cells with cell magics contain valid code, e.g. `%%time`. Maybe we could do something similar to your idea of what to do with inline magics - check if what follows is valid Python code, and if it is, keep it, else ignore it?

I feel this gives a better user experience because we don't need to educate every user to ignore non python code cells for nbqa to work.

**Comment by MarcoGorelli** [comment]
Yes, that would be much better actually...we might not even need `--nbqa-ignore-cells` about that, and I'm always happy to remove things from the public API :smile:

I can give a go at this later if you like

**Comment by girip11** [comment]
We could open a separate issue or use this one to track the task. I can pick this up sometime later this week.

**Comment by MarcoGorelli** [comment]
OK let's keep this issue for it

And sure, if this overlaps with the work you already wanted to do for inline magics, I'll assign you

**Comment by MarcoGorelli** [comment]
closing as I think the current solution of `--process-cells` is good enough
