### ISSUE TITLE
[Suggestion] Ideas about ReviewNB

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#360]
I have come across https://www.reviewnb.com/ (see GH https://github.com/ReviewNB) some time back and didn't know what it was for but I recently looked into it and installed it as a GH.

It helps to review notebooks in PRs when we make changes to such files.

Also, it may be an idea to integrate `nbqa` (maybe long shot) into ReviewNB - worth playing around with the idea.

**Comment by MarcoGorelli** [comment]
Hi @neomatrix369 - the only notebooks we have are for testing purposes, and they're not  often changed, so IMO we can (for now) hold off from integrating reviewnb

> Also, it may be an idea to integrate nbqa (maybe long shot) into ReviewNB - worth playing around with the idea.

**Comment by neomatrix369** [comment]
> Hi @neomatrix369 - the only notebooks we have are for testing purposes, and they're not often changed, so IMO we can (for now) hold off from integrating reviewnb
> 
Okay. makes sense, no point just pilling up new tools/analysers if the usage isn't justifiable for it.

> > Also, it may be an idea to integrate nbqa (maybe long shot) into ReviewNB - worth playing around with the idea.

> Not sure what you mean, can you elaborate please?
I mean making ReviewNB use nbqa when their users review notebooks. Here's what the workflow could look like:
- when nbqa is enabled in ReviewNB config
- user reviews a notebook PR
- user sees annotations/warnings by nbqa about the formatting of the notebook as part of the review 

It's roughly what I'm envisioning, of course their maintainer might have other plans or workflow in mind. But it's a good way to introduce nbqa to new ReviewNB users.

**Comment by MarcoGorelli** [comment]
OK, I see - convincing reviewnb to incorporate this into their review process would be too awesome to be true, but I can't really see it happening (for one thing, users wouldn't necessarily agree to their choice of formatter/linter), and because they seem to be focused on clear and understandable _diffs_ between notebooks, rather than on the contents of the notebooks themselves. And their source code isn't open source so we can't extend it, as far as I can tell

**Comment by neomatrix369** [comment]
> OK, I see - convincing reviewnb to incorporate this into their review process would be too awesome to be true, but I can't really see it happening (for one thing, users wouldn't necessarily agree to their choice of formatter/linter), and because they seem to be focused on clear and understandable _diffs_ between notebooks, rather than on the contents of the notebooks themselves. And their source code isn't open source so we can't extend it, as far as I can tell

Let's see if we can come up with something is the meanwhile I'll continue to be an "ideas" hamster running on the mill!

**Comment by MarcoGorelli** [comment]
:rofl: sure, please do keep the ideas coming!

**Comment by neomatrix369** [comment]
@MarcoGorelli I'll try to propose the idea to them and leave it to them to integrate it, we don't lose anything for asking
