### ISSUE TITLE
Package default configs in separate toml file

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#391]

**Comment by MarcoGorelli** [comment]
closed in #408

**Comment by s-weigand** [comment]
If you add `closes #<issue_number>` in a separate line in a PR comment, the issue will be autoclosed ^^

**Comment by MarcoGorelli** [comment]
True, I usually try to do that but this time I forgot I'd already opened an issue :joy:

**Comment by s-weigand** [comment]
Just saw that in the other PRs 😂
