### ISSUE TITLE
Make all methods public

### ISSUE THREAD

**Issue by s-weigand** [nbQA-dev/nbQA#397]
Since `nbqa` is first and foremost a CLI tool and not a library that exposes an official API, IMHO there is no needs to make functions/classes private (prepending `_` to the name).
Maybe I'm just missing a point, so always willing to learn 😄

**Comment by girip11** [comment]
> there is no needs to make functions/classes private (prepending _ to the name)

By exposing only necessary methods/classes/constants from a module, we make the developers stick to a design. If you make all the methods public, then the developer discipline goes away. We will start thinking what is the harm in calling this method from this module, its public anyway. Having module private and public entities are very much required for smooth maintenance of this project. That's my thought process.

**Comment by MarcoGorelli** [comment]
not sure there's much traction here, I have no strong opinions here - PRs are welcome, but I'll close the issue to reduce the queue
