### ISSUE TITLE
Output from 'nbqa black' has line numbers referring to Python script, not Jupyter notebook

### ISSUE THREAD

**Issue by Daniel-Mietchen** [nbQA-dev/nbQA#399]
I was testing the command

```Python
nbqa black notebook.ipynb --nbqa-mutate
```

from [here](https://github.com/nbQA-dev/nbQA/issues/289#issuecomment-712199396) and while figuring out dependencies (black was missing) ended up having that command in a code cell in the active notebook I wanted to test the mutation on, with the path to the notebook (stated as ```correctpath``` below) originally mis-specified (stated as ```wrongpath``` below). 

When calling the command (from a terminal) on that notebook, with the path specified correctly, I got the error message

```Python
error: cannot format correctpath/notebook.ipynb: Cannot parse: 38:5: nbqa black wrongpath/notebook.ipynb --nbqa-mutate
Oh no! 💥 💔 💥
1 file failed to reformat.
```

I would expect nbQA to warn about the missing file, but not fail because of it.

**Comment by MarcoGorelli** [comment]
Hey @Daniel-Mietchen 

Thanks for the report! This was fixed yesterday (#393), we just hadn't made a release yet. I'll fix something else up and then I'll push out a new version

**Comment by MarcoGorelli** [comment]
I've made a new release (0.3.6), if you could try it out and let us know if the issue isn't fixed we'd really appreciate it :pray:

**Comment by Daniel-Mietchen** [comment]
@MarcoGorelli I just [retested](https://public.paws.wmcloud.org/12410844/100days/100days-Day-041.ipynb) it with the new version 0.3.6, and the error message remained the same.

**Comment by MarcoGorelli** [comment]
Hi @Daniel-Mietchen 

Thank you so much for your report! I can't reproduce this though: I just downloaded the notebook, ran it, and this is what I see:
![image](https://user-images.githubusercontent.com/33491632/97800554-fab1e280-1c2d-11eb-98fe-4870acda2064.png)

I'm thinking about what the issue could be... @nbQA-dev/nbqa-core any ideas?

**Comment by MarcoGorelli** [comment]
I think I see what's happening - you actually _do_ have a notebook called <> saved, and that one has the line
```
nbqa black 100days/100days-Day-038.ipynb --nbqa-mutate
```
which is not valid Python syntax.

So, I think it's correct that this error message is shown

**Comment by Daniel-Mietchen** [comment]
Yes, changing the line numbers such that they refer to the notebook cell rather than the script would make sense. 

I wasn't aware that nbQA is meant to fail reformatting a notebook if there is wrong syntax anywhere in any cell, but I agree that this makes sense in a lot of contexts.

The set of notebooks that I am currently working on is meant to test the documentation of learning processes though, which means I want to encourage students (or anyone else who happens to come upon such resources) to see the mistakes as well as the processes they trigger towards any solutions. With that in mind, I essentially avoid re-running a cell to fix a problem, and I want to encourage students to do the same. 

Ideally, a tool like [Provbook](https://github.com/Sheeba-Samuel/ProvBook) would keep track of the different versions of a given cell, so the errors and associated learning process could still be documented, and nbQA (especially with a --nbqa-diff flag, as per #352 ) could assist in finding a solution by pointing out some obvious things to check.

**Comment by MarcoGorelli** [comment]
> I wasn't aware that nbQA is meant to fail reformatting a notebook if there is wrong syntax anywhere in any cell, but I agree that this makes sense in a lot of contexts.

**Comment by MarcoGorelli** [comment]
> I wasn't aware that nbQA is meant to fail reformatting a notebook if there is wrong syntax anywhere in any cell, but I agree that this makes sense in a lot of contexts.

Currently, if the code quality tool you're running (in this case, `black`) throws an error when it finds invalid syntax, then so will `nbqa black`. If the code quality tool you're running doesn't throw errors on invalid syntax (e.g. isort doesn't), the neither will nqba (e.g. `nbqa isort Downloads/100days-Day-038.ipynb` doesn't error)

We _could_ do some hacking to avoid that, but I'm inclined to say we shouldn't

> Yes, changing the line numbers such that they refer to the notebook cell rather than the script would make sense.
