### ISSUE TITLE
DOC Add troubleshooting section

### ISSUE THREAD

**Issue by s-weigand** [nbQA-dev/nbQA#419]
As #346 has shown there are common problems that we could address in a troubleshooting guide.
My suggestion would be to split it into two parts:
- CLI usage
- pre-commit usage

Also, having two different issue templates for `CLI` and `pre-commit` bugs migth be useful since those require different information about the environment.

**Comment by s-weigand** [comment]
An example of a CLI problem would be:
- Formatter doesn't change notebook
  In order for nbqa to change files, you need to [allow mutation](https://nbqa.readthedocs.io/en/latest/configuration.html#allow-mutations).

**Comment by MarcoGorelli** [comment]
closing as --nbqa-mutate is no longer required
