### ISSUE TITLE
Error while processing cells with cell magics like `%%HTML`

### ISSUE THREAD

**Issue by girip11** [nbQA-dev/nbQA#421]
Some cell magics like HTML can be written as `%%html` or `%%HTML`. When one of the cells had `%%HTML` and `ignore_cells` option was not set, we would run in to trouble. Since we have hardcoded most of the cell magics to be ignored, I would like to exhaustively cover all cell magics for now.

Below cell magics are output of the ipython magic `%lsmagic`

`%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile`

What we have already covered
```Python
MAGIC = [
    "%%bash",
    "%%cython",
    "%%html",
    "%%javascript",
    "%%js",
    "%%latex",
    "%%markdown",
    "%%perl",
    "%%python2",
    "%%ruby",
    "%%script",
    "%%sh",
    "%%svg",
    "%%writefile",
]
```

Some cell magics like `%%HTML` are not covered. Add those missing cell magics(which don't contain any python3 code) to the list.

**Comment by MarcoGorelli** [comment]
closed in #426
