### ISSUE TITLE
iPython syntax protection

### ISSUE THREAD

**Issue by henryiii** [nbQA-dev/nbQA#445]
It seems some valid iPython syntax breaks this:

```
error: cannot format /private05-pybind/05-pybind.ipynb: Cannot parse: 8:7: pyinc = !python3-config --cflags
error: cannot format /private05-pybind/05b-pybind.ipynb: Cannot parse: 11:6: mkdir pyminuit2
```

I can make the mkdir magic explicit, %mkdir, but the `x = !...` line doesn't have an obvious fix.

**Comment by MarcoGorelli** [comment]
Thanks @henryiii for the report!

I'm not sure there's a simple fix here, we _may_ have to treat `x = !...` as a known limitation... @girip11 any thoughts?

**Comment by henryiii** [comment]
I would assume that `!...` is protected already, so `item = !...` should also be protected in a simliar way? I know that `!...` by itself doesn't break things.

**Comment by henryiii** [comment]
Basically this is not quite true: https://github.com/nbQA-dev/nbQA/blob/036332e96865994060159ac30d16dd5cdf29cc16/nbqa/handle_magics.py#L128 - `item = !` is also supported in IPython.

**Comment by MarcoGorelli** [comment]
You're right, we should fix this really...we'll keep it on the roadmap, thank you so much for having brought it to our attention!

In the meantime, perhaps this works for you as a workaround:
```
>>> import subprocess
>>> output = subprocess.run(['python3-config', '--cflags'], stdout=subprocess.PIPE, text=True)
>>> item = output.stdout
>>> item
'-I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-0aiVHW/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall\n'
```

**Comment by s-weigand** [comment]
Another workaround would be to use `_`, which is set to the last returned value.
```python
In [1]: "dummy return"
Out[1]: 'dummy return'

In [2]: foo = _

In [3]: foo
Out[3]: 'dummy return'
```

As for the general problem, we might be able to solve it using `nbconvert.filters.ipython2python` on whole cells, this also partially solves the 'indented line magic' problem.

A little example of how it would look like in this case.
```python
In [1]: from nbconvert.filters import ipython2python                                     
                                                                                         
In [2]: print(ipython2python("pyinc = !python3-config --cflags"))                        
pyinc = get_ipython().getoutput('python3-config --cflags')                               
                                                                                         
                                                                                         
In [3]: print(ipython2python("mkdir pyminuit2"))                                         
mkdir pyminuit2                                                                          
                                                                                         
                                                                                         
In [4]: print(ipython2python("%mkdir pyminuit2"))                                        
get_ipython().run_line_magic('mkdir', 'pyminuit2')                                       
                                                                                         
                                                                                         
In [5]: print(ipython2python("normal_python = True\npyinc = !python3-config --cflags"))  
normal_python = True                                                                     
pyinc = get_ipython().getoutput('python3-config --cflags')                               
                                                                                         
                                                                                       
In [6]: print(ipython2python("if True:\n    %timeit 1 + 1"))
if True:
    get_ipython().run_line_magic('timeit', '1 + 1')           
```

The big problem here is with the additional line length and mapping back to notebooks.
@girip11 is the expert for this 😄

**Comment by girip11** [comment]
> error: cannot format /private05-pybind/05b-pybind.ipynb: Cannot parse: 11:6: mkdir pyminuit2

@henryiii: This is because  currently nbqa doesnot support automagics. And as you mentioned, it can be mitigated by making it an explicit ipython magic.

> error: cannot format /private05-pybind/05-pybind.ipynb: Cannot parse: 8:7: pyinc = !python3-config --cflags

This is a genuine bug. I didn't know that we could use `!` magic for such a use case. 

> - item = ! is also supported in IPython. I believe you could search for = followed by 0 or more whitespace followed by !.

And as you rightly pointed out adding an extra check for such patterns to fix this issue.

**Comment by girip11** [comment]
@s-weigand Regarding using `nbconvert.filters.ipython2python`, I know you have brought it up before also. I also looked at how you have implemented for `flake8-nb`. I too wanted to use it, but it has the following limitations. 

* I wasn't able fix this issue https://github.com/nbQA-dev/nbQA/issues/279 using `ipython2python`
* Placing the import `from IPython import get_ipython` in the notebook can lead to issues with isort. Flake8 and pylint were also raising warnings on the import order.

These are the ones I could think of for not going with `nbconvert.filters.ipython2python`.

**Comment by henryiii** [comment]
Fun test case to add:

```python
check_me = "h = !ls"
```

The stuff on the left is limited to valid python assignments, that might be helpful. Though wrongly triggering on the above line and excluding it is likely better than what we have now.

**Comment by girip11** [comment]
@s-weigand: I used `nbconvert.filters.ipython2python` to detect ipython magic. But I am not doing anything more using its output. Without this function, identifying different forms of ipython magic becomes a nightmare.

@s-weigand  and @MarcoGorelli: I have taken dependency on "nbconvert>6.0.0" because starting from this version, they started supporting only `python >= 3.6` which is what nbqa also requires.

> Fun test case to add:
> `check_me = "h = !ls"`

@henryiii : Good catch!  Luckily  using `nbconvert.filters.ipython2python` api saves me from such python code.  

I have few test cases to add. I will raise a PR later today.

**Comment by s-weigand** [comment]
@girip11 The case of `flake8-nb` my solution was quite pragmatic since it is just a linter and you can simply ignore lines (also I didn't even know that multiline line magic was possible 😅 ).
Due to the generality (especially the formatter support of `nbqa`) the solution needs to be a lot more sophisticated.

My general idea of how it could work would be:
1. Use `ipython2python` on the whole cell to generate a `diff`
1. Use your awesome substitution-bookkeeping code on the `diff`-blocks
1. Run the tool on the intermediate file
1. Reapply the substitution-bookkeeping code

**Comment by MarcoGorelli** [comment]
> I have few test cases to add. I will raise a PR later today.

That was fast - you're a legend!

And sure, :+1: for adding these extra dependencies to identify cases of ipython magic

**Comment by girip11** [comment]
> The case of flake8-nb my solution was quite pragmatic since it is just a linter and you can simply ignore lines (also I didn't even know that multiline line magic was possible sweat_smile ). Due to the generality (especially the formatter support of nbqa) the solution needs to be a lot more sophisticated.

@s-weigand  You have captured this very well. Using `nbconvert.filters.ipython2python` made detecting ipython magics easier and less error prone. Thanks for bringing this API to our notice. Also by any chance, have you come across nbconvert API for automagic detection. With `%automagic ON` one does not even need to prefix line magics with `%`.

**Comment by henryiii** [comment]
I would rather expect automatic detection to require execution, since they can be loaded via load_ext?

**Comment by girip11** [comment]
@henryiii: You are right. I approached it from the point that somehow it was able to detect `mkdir somedir` as automagic. So I thought there should be some logic inside **nbconvert** to detect these as magics without executing them. But it may not be the case. And for the magics loaded via `load_ext` magic, we would definitely require execution context.

**Comment by MarcoGorelli** [comment]
The difficulty I'm seeing here is how to round-trip - how do we know whether `.get_output` came from `!` or `!!`?
```python
>>> TransformerManager().transform_cell("flake8_version = !flake8 --version")
"flake8_version = get_ipython().getoutput('flake8 --version')\n"
>>> TransformerManager().transform_cell("!!flake8 --version")
"get_ipython().getoutput('flake8 --version')\n"
```

**Comment by MarcoGorelli** [comment]
have started #606 to do this...maybe we can actually get there. Hoping to get it done this week and then to release 0.11.0 by Monday

cc @ravwojdyla @henryiii if either of you have many notebooks in which you use magics beyond the magics (e.g. more complex cases than just `%matplotlib inline` at the top of the notebook), then it would be really useful if you could share them
