### ISSUE TITLE
IPython.core.inputsplitter (which ipython2python uses) is deprecated

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#459]
see https://github.com/jupyter/nbconvert/issues/1388

not really sure what to do about this but it might be worth keeping an eye on

**Comment by girip11** [comment]
I thought of removing `nbconvert` and using directly `IPython` for converting magics to python code. While doing so, I observed a different behavior when using `transform_cell` in `inputsplitter` and `inputtransformer2`. I filed this bug along with the possible fix [here](https://github.com/ipython/ipython/issues/12706)

**Comment by MarcoGorelli** [comment]
Nice, that looks like the kind of bug report every maintainer dreams of receiving :rofl:

**Comment by MarcoGorelli** [comment]
closing as we're now using `TransformerManager`, despite its limitations, as multi-line magics are ignored
