### ISSUE TITLE
Tests which delete files should run in temporary directory

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#472]
Sometimes tests fail, and we get a whole load of modified files (e.g. `.flake8`, `setup.cfg`, `tests/__init__.py`) - any test which modifies them or has the potential to delete them should probably make sure that such modifications don't persist if the test fails

**Comment by s-weigand** [comment]
That also is a problem if you want to run tox in parallel (`tox -p`).

A `run_in_tempdir` context manager/fixture, which copies the files and uses `os.chdir`, would probably be the best solution.

**Comment by MarcoGorelli** [comment]
I think this is mostly fine now
