### ISSUE TITLE
Black removing first character of the first code cell in nb

### ISSUE THREAD

**Issue by ncoop57** [nbQA-dev/nbQA#500]
Hi, I am using `nbqa==0.5.3` and `black==20.8b1` and have the following notebook:

![image](https://user-images.githubusercontent.com/7613470/101266948-a95fac00-3721-11eb-97d7-176626a85104.png)

Here is a link to the notebook if that helps: https://drive.google.com/file/d/1EyZlfuoAbQycPYY92ysJ03-5lBuE0VlE/view?usp=sharing

As you can see the first cell has this special comment I need for another library I use. When I run `nbqa black 00_core.ipynb --nbqa-mutate`, I get the following output:

![image](https://user-images.githubusercontent.com/7613470/101266974-00658100-3722-11eb-8ed4-437bc4d6e8f8.png)

For some reason, it deletes the comment symbol. Any idea why this is happening or if this is expected? Any help would be greatly appreciated, thanks!

BTW, really like the project!

**Comment by ncoop57** [comment]
Also, this doesn't for some reason happen if I places a cell with a number in it before the cell with the comment symbol:

![image](https://user-images.githubusercontent.com/7613470/101267026-8f729900-3722-11eb-879c-718eca907d2b.png)

Which is what I've been having to do, but its ugly :(

**Comment by MarcoGorelli** [comment]
Hey @ncoop57 

Thanks for the report! This is not expected and is something I wasn't aware of - I'll look into it and'll get back to you when I have a fix!

> BTW, really like the project!

Thanks, and thanks for reporting a bug (which helps make it better!)

**Comment by MarcoGorelli** [comment]
:thinking: I can't reproduce this:
```console
$ nbqa black 00_core.ipynb --nbqa-mutate
All done! ✨ 🍰 ✨
1 file left unchanged.
```

Is this the exact notebook you ran? Do you have a pyproject.toml file in your repo with any settings set?

**Comment by girip11** [comment]
> I can't reproduce this
 Same here.

**Comment by ncoop57** [comment]
Whoops, sorry about that. The file I shared didn't have improper formatting and so black didn't format it. Here is a version that will get formatted by black: https://drive.google.com/file/d/1EyZlfuoAbQycPYY92ysJ03-5lBuE0VlE/view?usp=sharing

> Is this the exact notebook you ran? Do you have a pyproject.toml file in your repo with any settings set?

And no, I don't have a `pyproject.toml` file. The only settings I have are for `pycodestyle` to just ignore jupyter specific things like trailing semicolons, etc. So, I don't think that is the cause.

**Comment by MarcoGorelli** [comment]
You're right @ncoop57 , this indeed a bug! Can confirm this reproduces with the second version you sent in - we'll fix it

**Comment by MarcoGorelli** [comment]
found the bug, it's cause we're using `lstrip` incorrectly, will add a test and push a fix and make a new release soon

**Comment by MarcoGorelli** [comment]
@all-contributors please add @ncoop57 for bugs

**Comment by MarcoGorelli** [comment]
@ncoop57 If you upgrade to `nbqa` 0.5.4 this should be fixed - please do let us know if you run into any further issues or have any ideas to improve this project! Thanks again for your excellent report!

**Comment by ncoop57** [comment]
@MarcoGorelli just tried out 0.5.4 and its working perfectly!! Thanks for handling this so quickly!
