### ISSUE TITLE
Provide some stats about the kinds of changes made/ proposed

### ISSUE THREAD

**Issue by Daniel-Mietchen** [nbQA-dev/nbQA#521]
I have been looking a bit more into the ```--nbqa-diff``` flag (cf. https://github.com/nbQA-dev/nbQA/issues/352 ) as an educational tool.

One issue that came up when using nbqa on larger files is that it might be hard to keep (or even get) an overview of the kinds of changes that nbqa proposes.

For instance, I like to use the LIGO notebook at [https://github.com/minrk/ligo-binder/blob/master/index.ipynb](https://github.com/minrk/ligo-binder/blob/master/index.ipynb) for teaching, but when I run 
```nbqa black index.ipynb --nbqa-diff```
on it, there are many suggestions, so some filtering would be useful.

For instance, the following changes are frequently proposed by nbqa:
1. replace single quotes with double quotes
1. add missing space after hash sign
1. remove superfluous spaces before a hash sign

Now suppose the students have learned about the respective issues in their course or project, so it would be useful for them to be able to run nbqa iteratively (with or without the nbqa-diff flag) such that it
- only fixes a specified subset of these issues, leaving everything else intact (so further learning can concentrate on the remaining issues); or
- ignores such a specific subset (e.g. the original spacing in the example pictured below might be more didactically useful than what nbqa proposes)

<img width="674" alt="Screen Shot 2020-12-25 at 02 55 05" src="https://user-images.githubusercontent.com/465923/103126523-9a9f5180-465c-11eb-9312-7e34aa2c9b12.png">

I realize that such functionality would require some unique identification scheme for all of the things nbqa (and its dependencies like black) is handling, and I suspect that such a scheme might not be readily available, but since functionality in black and similar tools is typically built around specific PEPs ([example](https://github.com/psf/black/blob/d9884b6d330d56b2d2ea1d24f1bdf36ff433c0e6/tests/data/import_spacing.py)), there might be a possibility that I am simply missing, so I thought opening this ticket could be a useful way to get some more insights or other feedback on this.

**Comment by MarcoGorelli** [comment]
Hi @Daniel-Mietchen 

Thanks for the suggestion - TBH it's not really something I'd like to support, as it's not specific to notebooks. If some similar feature were implemented for `black` then we could think of using it too, but I wouldn't want to make something like this specifically for nbqa

**Comment by Daniel-Mietchen** [comment]
That's totally understandable. Thanks for considering it.
