### ISSUE TITLE
Proper way to use nbqa-mypy

### ISSUE THREAD

**Issue by ravwojdyla** [nbQA-dev/nbQA#543]
Thanks for your work! I have a question, that might convert into an issue, so I'm trying to use `nbqa-mypy`, my config looks like this:

```
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.7
    hooks:
      - id: nbqa-mypy
        args: ["--nbqa-ignore-cells=%%R", "--strict", "--show-error-codes"]
```

But I'm getting error about missing modules that are part of the repository, example:

```python
pipelines/notebooks/foo.ipynb:cell_2:1: error: Cannot find implementation or library stub for module named 'my_utils'  [import
```

Where the repo contains `{pipelines, my_utils}` in the root, and import from `my_utils` doesn't raise issues in py modules and vanilla mypy checks. Am I doing sth wrong? Is there a blessed way to use `nbqa-mypy` and give access to the main repo? Maybe `nbqa-mypy` is missing some step to add repo to the pre-commit's nbqa-mypy virtualenv?

**Comment by s-weigand** [comment]
Hi there, thanks for your report.

When you use `mypy` on `py` modules do you use it directly from the console (e.g. `mypy --strict --show-error-codes src`) or are you using it with `pre-commit`?
The `mypy` recommit hook has some default extra flags:
https://github.com/pre-commit/mirrors-mypy/blob/59a8e37f2ab16103e56845983e9a5900facfa856/.pre-commit-hooks.yaml#L6 

The important one being `--ignore-missing-imports`, which tells `mypy` not to complain if a 3rd party package has not stubs.

If this is a public repo, it would help if you could share it with us so we can have a look at the code 😄

**Comment by ravwojdyla** [comment]
👋 @s-weigand I use `pre-commit`, unfortunately not a public repo. Let me see if the `--ignore-missing-imports` helps, and what kind of error would that catch then. Will be back soon.

**Comment by ravwojdyla** [comment]
@s-weigand cool, that helped remove that error, thanks. So I'm going to close this issue in a minute, but in the meantime I also have a quick question, so I'm looking for a tool that would catch obvious bugs like wrong imports in notebooks from the repo. And I stumbled upon nbQA, unfortunately I'm having hard time solving that seemingly simple problem. Even with nbQA, the only tool that seems to provide that kind of check is pylint, but it also provides quite a bit of false-positives. Initially mypy would catch the error, but with `--ignore-missing-imports`, now everything is `Any`, so I'm back to square 1. Any tips?

**Comment by MarcoGorelli** [comment]
Thanks @ravwojdyla  for the report

I'll try to reproduce this later, but if `my_utils` is a local package then this feels like a bug to me

**Comment by ravwojdyla** [comment]
@MarcoGorelli thank you!! In that case I will keep this issue open. Looking forward to your reproduction.

**Comment by MarcoGorelli** [comment]
can reproduce (but don't yet have a solution, I thought that modifying PYTHONPATH here

https://github.com/nbQA-dev/nbQA/blob/bf2b6d794d5ea7227c1ea908a134ef8889ba25c2/nbqa/__main__.py#L410-L424

would've been enough, but evidently not) - I'll get back to you on this

Anyway, you're the first person to report a bug using `mypy`, and I'm pleased to see that there is at least one other person out there who has wanted to type check their notebooks!

**Comment by s-weigand** [comment]
If by `wrong imports in notebooks` you mean something like typos or missing packages, you could run the notebook on CI with [nbval](https://github.com/computationalmodelling/nbval) (given that they don't take ages to execute, e.g. training a ML model).

Another approach might be to remove the `--ignore-missing-imports` flag, [configure mypy to ignore 3rd party libraries](https://mypy.readthedocs.io/en/stable/config_file.html#examples) (e.g. `numpy`) and add `my_utils` as a [additional dependency in your pre-commit config for mypy](https://pre-commit.com/#config-additional_dependencies).

**Comment by s-weigand** [comment]
@MarcoGorelli nice catch :open_mouth:

**Comment by s-weigand** [comment]
My assumption was that `my_utils` is a package (folder with modules, which can be installed).

@ravwojdyla @MarcoGorelli  could you tests what happens if you use the `--scripts-are-modules` flag? 😄

**Comment by ravwojdyla** [comment]
> If by wrong imports in notebooks you mean something like typos or missing packages, you could run the notebook on CI with nbval (given that they don't take ages to execute, e.g. training a ML model).

@s-weigand yes, definitely something I'm aware of, but I would strongly prefer to leverage static analysis for this problem. We can assume that the problem is for example a missing symbol, say that there is `my_utils.foo`, but in the notebook I import `my_utils.bar`, I should be able to use `mypy` to flag that error. But I'm not religious about using `mypy` for this use case, if there is other tool that can do it at a similar cost. As mentioned above pylint seem to catch it BUT also includes other false-positives (including the same error category). 

> add my_utils as a additional dependency in your pre-commit config for mypy.

How would that work if `my_utils` is part of the repo? And why would the setup by so different from the pre-commit mypy? Also tried `--scripts-are-modules`, without installing the main repo, doesn't help. Appreciate your help.

**Comment by MarcoGorelli** [comment]
Seems like we need to set `MYPYPATH` in addition to `PYTHONPATH` https://mypy.readthedocs.io/en/latest/running_mypy.html 

Will make a new release over the weekend

**Comment by MarcoGorelli** [comment]
@all-contributors please add @ravwojdyla for bugs

**Comment by ravwojdyla** [comment]
Thanks @MarcoGorelli, looking forward to the new release!

**Comment by s-weigand** [comment]
@ravwojdyla The `additional dependency` idea was under the assumption that `my_utils` is a package in the repo and installed in the local env. 
I was just throwing ideas, based on assumptions. 😅 

Luckily it looks like @MarcoGorelli already found a solution 🎉

**Comment by MarcoGorelli** [comment]
@ravwojdyla could you please check whether this works for you in v0.5.8?

**Comment by ravwojdyla** [comment]
@MarcoGorelli thanks for the release. Results:
 * I noticed that the tag now includes `v` prefix for version `0.5.8`, is that intentional? Not that I mind one or the other, just want to signal it since other tags do not use that prefix.
 * `v0.5.8` seems to now include the current repo, which is great, and it for example recognises the missing symbol issue BUT there is an issue, I have mypy config stored in `setup.cfg` (which is one of the supported config files [doc](https://mypy.readthedocs.io/en/stable/config_file.html#the-mypy-configuration-file)), nbqa-mypy seems to ignore that config file. An example config to reproduce could be `ignore_missing_imports = True` for a particular lib.
 * I'm hitting https://github.com/nbQA-dev/nbQA/issues/455, are there any workaround for that?

**Comment by s-weigand** [comment]
@ravwojdyla Thanks for catching the prepended `v` in the tag.
@MarcoGorelli this might cause problems with `pre-commit` where the tag name is defined under `rev`, not to break things for people who already updated we should also push a tag `0.5.8`.

@ravwojdyla As for the config issue have a look at the [docs](https://github.com/glotaran/pyglotaran/pull/444/checks?check_run_id=1942091785) where we have an example with  `.mypy.ini`, I hope this solves your issue.

As for #455 maybe @MarcoGorelli knows a trick 😄

**Comment by MarcoGorelli** [comment]
Thanks for your quick feedback @ravwojdyla 

- indeed, that wasn't intentional, sorry about that - I've now renamed the tag to `0.5.8`
- I just tried that couldn't reproduce it (I put `ignore_missing_imports = True` in `setup.cfg`, and `nbqa mypy t.ipynb` respected it) - any chance you could send a reproducible example / show your full `setup.cfg` and notebook?
- I would suggest using `subprocess.run` and capturing the output. If you share your command I can try to be more specific

**Comment by ravwojdyla** [comment]
@MarcoGorelli Here's a public reproduction: https://github.com/ravwojdyla/_nbqa_example, see the readme.

**Comment by MarcoGorelli** [comment]
Thanks @ravwojdyla - I'm getting the same error if I run
```console
$ mypy pipelines/std.py 
pipelines/std.py:2: error: Cannot find implementation or library stub for module named 'pandas'
pipelines/std.py:2: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
pipelines/std.py:5: error: Name 'foo2' is not defined
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by MarcoGorelli** [comment]
Also, I think you need `[mypy]` in your `setup.cfg` file. If I change it to
```
[mypy]

[mypy-pandas.*]
ignore_missing_imports = True
```

then it works fine for me

**Comment by ravwojdyla** [comment]
@MarcoGorelli weird, `mypy pipelines/std.py ` doesn't give me the same error. But adding `[mypy]` does fix nbqa 🤔

**Comment by ravwojdyla** [comment]
@MarcoGorelli ah, ok, I think I found it, after upgrading `mypy`, I am getting the same errors as you. So this "obligatory" `[mypy]` must be a new feature.

**Comment by MarcoGorelli** [comment]
@ravwojdyla Yes, you're right - and if you change your `.pre-commit-config.yaml` file to
```
repos:
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.8
    hooks:
      - id: nbqa-mypy
        args: ["--nbqa-ignore-cells=%%R", "--strict", "--show-error-codes"]
        additional_dependencies: [mypy==0.782]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args: ["--strict", "--show-error-codes"]
```
(note the pinning of `mypy` in `additional_dependencies`)
then there is no extra import error from `nbqa-mypy` compared with `mypy`

**Comment by ravwojdyla** [comment]
@MarcoGorelli I think we are good then! Thanks. Btw, any tips about #455?

**Comment by MarcoGorelli** [comment]
I would suggest using `subprocess.run` and capturing the output. If you share your command I can try to be more specific

**Comment by ravwojdyla** [comment]
@MarcoGorelli ah, I understand that comment now! Perfect. Thank you!!
