### ISSUE TITLE
Add nbqa-prettier built-in hook

### ISSUE THREAD

**Issue by v-goncharenko** [nbQA-dev/nbQA#553]
What do you think of using [prettier](https://github.com/pre-commit/mirrors-prettier) pre-commit hook in nbQA?

I think it's useful since Jupyter Notebooks contain a lot of `markdown` text which needs to be formatted.

**Comment by MarcoGorelli** [comment]
Thanks @v-goncharenko for the idea!

Nbqa only looks at code cells, but i think this would be a great idea for a separate package!

**Comment by v-goncharenko** [comment]
Why separate package?

I mean since nbQA already parses notebook structure and has all the infrastructure for evaluating separate transforms against notebook cells it seems very natural to process all kinds of cells e.g. `markdown` ones.

So am I correct you wouldn't consider accepting a PR to extend nbQA to process non-code cells?

**Comment by MarcoGorelli** [comment]
Hey @v-goncharenko - there's been another request for running on markdown cells (#555), so I've decided to reconsider, thanks for your suggestion!

**Comment by v-goncharenko** [comment]
Okay, nice!

Currently I don't have time to make a PR for `prettier` but I guess in course of couple of months I hope to save some time or  just someone else would do =)

**Comment by hukkinj1** [comment]
FYI, there's also a Markdown formatter written in Python https://github.com/executablebooks/mdformat :smile:

**Comment by MarcoGorelli** [comment]
closing in favour of #555 - thanks for your inputs!

**Comment by MarcoGorelli** [comment]
Hi @v-goncharenko @hukkin - as of `1.2.0`, `nbQA` now has an `--nbqa-md` flag, which allows to process Markdown cells instead of code cells

E.g.:
```console
$ nbqa mdformat tests/data/notebook_for_testing.ipynb --nbqa-md --nbqa-diff
Cell 2
------
--- tests/data/notebook_for_testing.ipynb
+++ tests/data/notebook_for_testing.ipynb
@@ -1,2 +1 @@
-First level heading
-===
+# First level heading

To apply these changes, remove the `--nbqa-diff` flag
```

**Comment by MarcoGorelli** [comment]
Also cc @choldgraf as it looks from [here](https://twitter.com/psychemedia/status/1455192710722334722) that you were also interested in this
