### ISSUE TITLE
Make cell-magics opt-in rather than opt-out

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#557]
Currently, nbqa tries to process all cell magics _except_ those in 

https://github.com/nbQA-dev/nbQA/blob/a99e0e2413c7af340ba994f86752bb29b8b36a82/nbqa/save_source.py#L31-L51

I think we should do the opposite: _never_ process cell magics, except for some hard-coded common ones like `matplotlib inline` and `timeit`, + add a command-line argument so users can pass extra ones they might want to process

This means deprecating `nbqa_ignore_cells` and instead adding `nbqa_process_cells`.

IMO it's OK to make a 0.6.0 release with this breaking change in - this is a relatively new project, and it's not like the user-base is large enough that we need to go through a deprecation cycle

cc @nbQA-dev/nbqa-core in case anyone has any comments - else I'll try to work on during the weekend

**Comment by girip11** [comment]
@MarcoGorelli: Should we give a deprecation warning and then remove it in the 0.6.1? Do you think keeping both old and new flags would be difficult for 1 or 2 releases ? I was thinking of making a simple change like `nbqa_process_cells` will get removed from the current ignore list in the code. So that it not a breaking change for now.

But I am completely agree with you on users giving what to process rather than nbqa expecting what to ignore.

**Comment by MarcoGorelli** [comment]
I'd suggest keeping the old flag but just letting it throw a a loud and clear error telling users that it's no longer valid. Having both flags seems a bit too complicated to me

> Should we give a deprecation warning and then remove it in the 0.6.1?

I think it'd be more typical to remove in the next minor release (0.7.0), which is a bit too far away - either way, without having yet reached 1.0.0, we're not yet bound by such rules and can make bigger changes without warning

**Comment by girip11** [comment]
> I'd suggest keeping the old flag but just letting it throw a a loud and clear error telling users that it's no longer valid. 

This is fine. The reason why I hesitated was some of the projects in the used by section contains big ones. So if the flag is removed, wouldn't their CI start failing?

**Comment by MarcoGorelli** [comment]
That's a good point, though which of those projects uses the flag? I had a look, but couldn't find any of them using it

**Comment by girip11** [comment]
Then you could proceed removing the flag.

**Comment by s-weigand** [comment]
IMHO making the option error or at least warn that it will be ignored, and point to this issue or somewhere in the docs is the most user-friendly and yet simple solution.

**Comment by MarcoGorelli** [comment]
Yup - have gone with erroring in #559
