### ISSUE TITLE
ReadTheDocs latest/stable are both old

### ISSUE THREAD

**Issue by bdice** [nbQA-dev/nbQA#579]
ReadTheDocs latest and stable tags appear to be stale.

The latest branch points to 0.6.1 instead of 0.7.1:
https://nbqa.readthedocs.io/en/latest/history.html

The stable branch points to 0.3.6:
https://nbqa.readthedocs.io/en/stable/history.html

I suggest pointing `latest` to the `master` branch and `stable` to the most recent tag (0.7.1 as of this writing). It is also possible to run [RTD builds for every pull request](https://docs.readthedocs.io/en/stable/pull-requests.html).

Fixing this requires project permissions on ReadTheDocs. @MarcoGorelli I'd be happy to help if desired. My ReadTheDocs username is the same as my GitHub username. 👍

I noticed this because I couldn't find the new support for yapf #547 in the docs, and couldn't add a link to the README as @MarcoGorelli suggested in a comment. 😄

**Comment by MarcoGorelli** [comment]
Hey @bdice - thank you so much for alerting me of this! I've rebuilt the docs and added you as maintainer on ReadTheDocs

**Comment by s-weigand** [comment]
RTD also has hooks to automatically change the default branch e.g. if a new tag was created.
I wish all those cool settings were also available via the `readthedocs.yml` and not only the web UI.

**Comment by bdice** [comment]
@MarcoGorelli Thank you! Also I saw you added yapf to the README -- thanks for that.

I would suggest enabling PR builds for ReadTheDocs. It shows up as a CI check and shows the docs for that pull request.

It can be enabled here if you like the idea: https://readthedocs.org/dashboard/nbqa/advanced/

![image](https://user-images.githubusercontent.com/3943761/116835862-e96c7300-ab89-11eb-8ca6-fe54d46e4d50.png)

https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html

**Comment by MarcoGorelli** [comment]
Thanks, done!
