### ISSUE TITLE
mention other projects to look into

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#58]
flake-nb, black-nb, nb-black. autoformatter...

**Comment by neomatrix369** [comment]
Take a look at this list here https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/Programming-in-Python.md#static-analysis

**Comment by MarcoGorelli** [comment]
Thanks @neomatrix369 ! If you know of any notebook-related code quality projects I should be aware of please do let me know!

**Comment by neomatrix369** [comment]
I came across this on LinkedIn
https://www.linkedin.com/posts/philipvollet_python-python3-analyst-activity-6693389309015412736-yyJq

VSCode Extension https://lnkd.in/gQVZQuN
Blogpost https://lnkd.in/gxJiPni

Worth a peek - may tangentially be related to your work

**Comment by MarcoGorelli** [comment]
Ooh, great, thanks @neomatrix369 ! I'll definitely try using that locally (though it doesn't look like I can use it as a pre-commit hook, or during CI, so unfortunately it doesn't render `nbQA` obsolete)

**Comment by neomatrix369** [comment]
> Ooh, great, thanks @neomatrix369 ! I'll definitely try using that locally (though it doesn't look like I can use it as a pre-commit hook, or during CI, so unfortunately it doesn't render `nbQA` obsolete)

Every tool has it's space, there will always be users for it. But play around and see if you can integrate it into your stuff! I see a small overlap but you know your tool better. I haven't played with Gather to find its strengths and weaknesses yet.
