### ISSUE TITLE
nbQA mistakenly reports formatting symbol as invalid syntax because it detects it as IPython magic

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#594]
xref https://github.com/yt-project/yt/pull/3287 : 

```python
(Pdb) !line
'    % hot_ad["temperature"]\n'
(Pdb) IPythonInputSplitter().transform_cell(line)
'get_ipython().run_line_magic(\'hot_ad\', \'["temperature"]\')\n'
```

I'm tempted to just stop trying to handle inline magic, it's too complicated and unreliable and they don't come up particularly often anyway. Will try to get something together at the weekend

**Comment by s-weigand** [comment]
Not handling inline magic might also lead to problems, remember this code we didn't know was valid before someone opened an issue to support it? 😅  
https://github.com/nbQA-dev/nbQA/blob/7725b793ce1ca0675a79f2fb1358b747f282f07e/nbqa/handle_magics.py#L292-L295

Not sure about how much of a performance impact it would be, but a possibly more robust way to check if a cell contains magic might be to call `IPythonInputSplitter().transform_cell` on the whole cell, check if the source changed and only handle it differently if it does.

Btw. I guess this is also the reason why `pyupgrade` isn't [replacing this old-style percent formatting](https://github.com/asottile/pyupgrade#printf-style-string-formatting).

**Comment by MarcoGorelli** [comment]
> I'm pretty tempted to just ignore any cell which contains line magics and just treat that as a known limitation

I think I was being overly negative when I wrote that - in #595, we can handle cells with line magics and handle this bug. It does mean giving up on checking Python code _within_ a line magic command, but that's a limitation I'm happy to live with for now
