### ISSUE TITLE
Skipped cells cause downstream/upstream problems with references for flake8

### ISSUE THREAD

**Issue by ESKYoung** [nbQA-dev/nbQA#617]
**OS**: macOS Big Sur 11.4
**Python**: 3.8.7
**Python packages**: nbQA (0.13.0), flake8 (3.9.2)

Thanks for adding the skipping cells using tags functionality! It appears to skip parsing of the cell content as well, which leads to downstream/upstream issues of missing variables, package imports, etc. 

### `pyproject.toml`:
```toml
[tool.nbqa.skip_celltags]
flake8 = ["skip-flake8"]
```

### `mwe.ipynb`

<details>
<summary>
Jupyter notebook with an <code>E231 missing whitespace after ','</code> error in the second cell
</summary>
<p>

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fd84a0df",
   "metadata": {},
   "outputs": [],
   "source": [
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c9a3834",
   "metadata": {
    "tags": [
     "skip-flake8"
    ]
   },
   "outputs": [],
   "source": [
    "a = random.randint(1,100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ae739825",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(a)"
   ]
  }
 ],
 "metadata": {
  "celltoolbar": "Tags",
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

</p>
</details>

### Command line execution

```shell
nbqa flake8 mwe.ipynb 
```

### Errors returned

```shell
mwe.ipynb:cell_1:1:1: F401 'random' imported but unused
mwe.ipynb:cell_3:1:7: F821 undefined name 'a'
```

**Comment by MarcoGorelli** [comment]
Hi @ESKYoung 

thanks for your report

I'm not sure I understand - the cell contains the `skip-flake8` tag, and so nbQA skips that cell. What would your expected output have been? What do you think `skip_celltags` should do?

**Comment by MarcoGorelli** [comment]
Ah I see, you just wanted that cell to be skipped from the output. I don't know if there's much nbQA could do about that given how it currently works, in the meantime you probably want to have a look at @s-weigand 's [flake8-nb](https://github.com/s-weigand/flake8-nb)

**Comment by ESKYoung** [comment]
Yep, nbQA is behaving as expected (apologies my misunderstanding), but this causes other flake8 issues to be raised that don't exist in reality. 

In the MWE, because cell 2 is skipped, I assume nbQA does not parse it (expected behaviour), but then this leads to the flake8 undefined name error in cell 3 because the variable `a` is defined in cell 2 (which was skipped!).

**Comment by MarcoGorelli** [comment]
ok, thanks - I'll close for now as out-of-scope for nbQA, but maybe could reconsider it in the future

**Comment by MarcoGorelli** [comment]
> Thanks I'll have a look at flake8-nb for the flake8-side of things then! Happy for you to close this!

flake8-nb will break on some valid IPython magics, e.g. if you have

```python
my_ls = !ls
```

it'll throw

```
$ flake8-nb mcve.ipynb 
mcve.ipynb#In[1]:1:9: E999 SyntaxError: invalid syntax
```

even though it's valid:
```python
In [1]: my_ls = !ls

In [2]: my_ls
Out[2]: ['mcve.ipynb', 'out', 'tmpdir', 't.py', 'venv', 'walk.py']
```

@s-weigand maybe we should make a `ipython-to-python-rt` library to share between nbqa and flake8-nb which'll do the magic handling?
