### ISSUE TITLE
Is extend-ignore taken into account?

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#669]
Just noticed this

https://github.com/ComPWA/ampform/commit/7d400055fc070a719127ed87b1c0e8693acd47c3

> * ci: use ignore instead of extend-ignore
  nbQA does not take extend-ignore into account

I haven't looked into this yet, just opening an issue for it so I don't forget - if that's the case, it sounds like a bug

(cc @redeboer)

**Comment by redeboer** [comment]
Oh haha well spotted :sweat_smile: 
Sorry should have reported that upstream, but yes I got that impression from a quick glance
