### ISSUE TITLE
`var = %env var` does not roundtrip

### ISSUE THREAD

**Issue by danielsparing** [nbQA-dev/nbQA#679]
`var = %env var` is used to assign an environment variable's value to a Python variable.

When running e.g. `nbqa black` (or `isort`, `pyupgrade` etc) on a cell containing such a construct, it gets transformed to the equivalent but harder to read `var = get_ipython().run_line_magic("env", "var")`.

It would be great if this remained unedited.

**Comment by MarcoGorelli** [comment]
Hey @danielsparing - thanks for reporting this, that's not intentional, it's definitely a bug. I'll have a think about how to fix it

**Comment by MarcoGorelli** [comment]
PR on its way - this probably affects upstream `black` as well

**Comment by MarcoGorelli** [comment]
@danielsparing this should be fixed in nbQA version 1.2.2, would really appreciate it if you could check and report back if that's not the case

Thanks again for your report!

**Comment by MarcoGorelli** [comment]
@all-contributors please add @danielsparing for bugs

**Comment by danielsparing** [comment]
> @danielsparing this should be fixed in nbQA version 1.2.2, would really appreciate it if you could check and report back if that's not the case
> 
> Thanks again for your report!

Yes, this fixes it! Thanks for much for the quick solution.
