### ISSUE TITLE
Support for code complexity/maintainability analysis tools.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [nbQA-dev/nbQA#686]
Wondering if it's possible to provide a pre-commit hook for the complexity/maintainability analysis tools such as wily. That will be really helpful!

**Comment by MarcoGorelli** [comment]
Hi @Sreerag-ibtl 

That should be possible - can you show me the command which you'd run on a Python file to see the complexity/maintainability?

**Comment by Sreerag-ibtl** [comment]
Sure. I use [Wily](https://github.com/tonybaloney/wily) and they have a [pre-commit hook](https://github.com/tonybaloney/wily/blob/master/.pre-commit-config.yaml) as well. I tried this [nbqa guide](https://nbqa.readthedocs.io/en/latest/pre-commit.html#custom-hooks) but couldn't make it work. Their CLI tool involves multiple steps. You can find it [here](https://github.com/tonybaloney/wily#command-line-usage).

**Comment by MarcoGorelli** [comment]
Just checked their repo and it says

> Wily will detect and scan all Python code in .ipynb files automatically.

So, looks like they already run on notebooks - if that's not the case, I'd suggest opening an issue in their repo

Thanks anyway for your suggestion!
