### ISSUE TITLE
flake8 doesn't recognize magic command

### ISSUE THREAD

**Issue by subpath** [nbQA-dev/nbQA#691]
Hey! I'm getting the following error when I'm using the `%pylab inline` command: 
```
Foo.ipynb:cell_2:1:1: F821 undefined name 'pylab'
```
Is it expected?
Steps to recreate this error:
notebook:
```
%pylab inline


pylab.plot([1, 2, 3], [1, 2, 3])
```
ndqa:
```bash
nbqa flake8 Foo.ipynb
```

**Comment by MarcoGorelli** [comment]
Hey @subpath 

Yes, it looks like `pylab` magically imports `matplotlib` objects, but that's not something that can be detected by a static analysis tool like `flake8` which doesn't run your code.

So I don't think there's much we can do here

Thanks anyway for the report, much appreciated, please do let me know if you run into anything else!
