### ISSUE TITLE
flakeheaven

### ISSUE THREAD

**Issue by RoyalTS** [nbQA-dev/nbQA#695]
I would love to run note plain flake8 but flake8 as wrapped by [flakeheaven](https://github.com/flakeheaven/flakeheaven). Alas, that appears to be difficult [given how nbqa is currently architected](https://github.com/flakeheaven/flakeheaven/issues/17). Can you think of a fix for this that the authors of flakeheaven haven't yet thought of. Alternatively, would you be willing to go down any of the routes proposed in the linked issue?

**Comment by MarcoGorelli** [comment]
Hey - yeah I'd like to go down this route https://github.com/flakeheaven/flakeheaven/issues/17#issuecomment-1014799078

Would you like to submit a pull request?

**Comment by RoyalTS** [comment]
I'm not sure I have the necessary chops to do that sadly :(

**Comment by MarcoGorelli** [comment]
no worries - I'll get to this when I get a chance then, no promises about timings though

**Comment by RoyalTS** [comment]
I'm not in any rush. Thank you very much in advance!
