### ISSUE TITLE
Magic in first cell or cells leads to flake8 E402

### ISSUE THREAD

**Issue by LauraRichter** [nbQA-dev/nbQA#700]
I have some notebooks with magics either:
* in their own in the first cell in my notebook (e.g. %load_ext nb_black), or
* at the top of the first cell where I have my imports (e.g. %load_ext autoreload and %autoreload 2\n"

This causes a flake8 E402 error because of code being about the imports.

I can ignore these by either #noqa E402-ing every import line, or by ignoring E402 throughout.

Which is ok, but I thought I'd but in a request to handle this nicely in nbqa
I don't know how other people see it, but I don't think having magics above the imports philosophically violates E402.

**Comment by MarcoGorelli** [comment]
One suggestion would be to [skip such cells based on cell tags](https://nbqa.readthedocs.io/en/latest/configuration.html#skip-cells-based-on-celltags)

**Comment by LauraRichter** [comment]
(Don't know how I managed to close the issue right after making it, oops!)

**Comment by LauraRichter** [comment]
If people think this change is worth making I thought I could try implement it? To make E402 not apply for magics? (Not sure how, I'd have to figure it out!)

**Comment by MarcoGorelli** [comment]
I meant that the user can set a cell-tag in their own notebook, in the first cell, if they don't want flake8 to report on it

> To make E402 not apply for magics? (Not sure how, I'd have to figure it out!)

The issue is that magics sometimes come with valid Python code, e.g.
```
%%timeit
my_func()
```
so I'd rather not exclude magics completely.

IMO skipping a cell you don't want to have errors reported on with a cell-tag is a simple-enough solution

**Comment by MarcoGorelli** [comment]
Thinking about this again, if a cell contains a magic - and nothing else - then I think we should be safe to always ignore it, right?

**Comment by MarcoGorelli** [comment]
> If people think this change is worth making I thought I could try implement it

Sure, do you want to try opening a pull request @LauraRichter ? I think you'd probably want to modify this function https://github.com/nbQA-dev/nbQA/blob/f2c53d45507058189cda0dab8958d50bd5401aa8/nbqa/save_code_source.py#L254-L306 and make it return true if a cell starts with `%`, `?`, or `!` and it is only one line long

See [here](https://nbqa.readthedocs.io/en/latest/contributing.html) for the contributing guide

**Comment by MarcoGorelli** [comment]
@all-contributors please add @LauraRichter for ideas

**Comment by MarcoGorelli** [comment]
fixed in version 1.3.0 :rocket:
