### ISSUE TITLE
Unexpected line ending format

### ISSUE THREAD

**Issue by stefaneidelloth** [nbQA-dev/nbQA#711]
I use LF line endings in Jupyter Notebooks and the pylint option

`expected-line-ending-format='LF'`

Unfortunately, nbqa replaces LF line endings with CRLF line endings when converting the notebooks to *.py files.
And then, I get unexpected pylint warnings. 

`Unexpected line ending format. There is 'CRLF' while it should be 'LF'. (unexpected-line-ending-format)`

=> How can I tell nbqa to keep LF line endings on Windows 10?

**Comment by MarcoGorelli** [comment]
Hey @stefaneidelloth thanks for your report

There's not currently a way to do this. 

Do you know it could be implemented? (I don't use Windows myself and don't really know much about line endings)

**Comment by stefaneidelloth** [comment]
The files are currently written with

```
with open(file_descriptor, "w", encoding="utf-8") as handle:
        handle.write(result_txt)
```

The open method has an optional argument "newline". 
Would be great if I could specify that in a configuration file for nbqa or pass it as a command line argument. 

https://stackoverflow.com/questions/2642036/using-python-to-write-text-files-with-dos-line-endings-on-linux

**Comment by MarcoGorelli** [comment]
Thanks

Not totally keen on adding extra configuration for this - would it be possible to detect the line ending of the `.ipynb` file and use that?

**Comment by MarcoGorelli** [comment]
@stefaneidelloth Do you get the same error if you first run `reorder-python-imports` on your Python files? It seems that they also just do `open` without specifying `newline`

https://github.com/asottile/reorder_python_imports/blob/9bac6bbf4fa776d5990163e00c43c13b05ab2191/reorder_python_imports.py#L496-L497

Is there any existing tool which preserves newlines I could take a look at?

**Comment by MarcoGorelli** [comment]
seems like `black` does this actually:

https://github.com/psf/black/blob/71e71e5f52e5f6bdeae63cc8c11b1bee44d11c30/src/black/__init__.py#L890-L903

Could that work for you? If so, do you want to open a PR?

**Comment by MarcoGorelli** [comment]
closing for now as there's been no uptake / interest in this

however, anyone's free to submit a PR if they want to see this feature in nbQA

**Comment by stefaneidelloth** [comment]
Thank you for asking back and sorry for the late reply. I decided to disable the line ending check for notebooks and closing the ticket is fine for me.
