### ISSUE TITLE
Ensure that committed Jupyter notebooks contain no outputs

### ISSUE THREAD

**Issue by joDancker** [nbQA-dev/nbQA#740]
This is not an issuse but perhaps an idea for a feature if it is not out of scope for `nbQA`

If one wants to commit a Jupyter notebook to a repository they want to ensure correct styling using pre-commit hooks. However, they might also want to commit without the outputs of the notebook. 

Currently one would need to include an additional repo in the pre-commit.yaml alongside `nbQA`. For simplicity would it make sense to include such cleaning in `nbQA`, ensuring a high quality of the jupyter notebooks? Perhaps something as in [gitlab.com/iamlikeme/nbhooks](https://gitlab.com/iamlikeme/nbhooks)

**Comment by MarcoGorelli** [comment]
thanks for the suggestion, but isn't this exactly what [nbstripout](https://github.com/kynan/nbstripout) does?

**Comment by joDancker** [comment]
> isn't this exactly what [nbstripout](https://github.com/kynan/nbstripout) does?

Yes, you are right.

Perhaps there is a way for integrating [nbstripout](https://github.com/kynan/nbstripout) without duplicating the work. I am not sure if they'd support something like that.

**Comment by MarcoGorelli** [comment]
closing then as out-of-scope
