### ISSUE TITLE
Working with pipx?

### ISSUE THREAD

**Issue by yibenhuang** [nbQA-dev/nbQA#756]
Hi there,

I've installed a couple of tools by [pipx](https://github.com/pypa/pipx), as I want to them installed globally while working on jupyter notebooks in different virtual environments. So I tried to install `nbqa` by `pipx` as well, but it turned out that `nbqa` could not find the other tool modules.

Below is the output of `pipx list`.

```
 package black 22.8.0, installed using Python 3.10.6
  - black
  - blackd
 package flake8 5.0.4, installed using Python 3.10.6
  - flake8
 package isort 5.10.1, installed using Python 3.10.6
  - isort
  - isort-identify-imports
 package nbqa 1.5.2, installed using Python 3.10.6
  - nbqa
 ```

And if I run `nbqa black test.ipynb`, it will raise the error `ModuleNotFoundError: Command black not found by nbqa.`

Wondering what would be the workaround, thanks!

**Comment by MarcoGorelli** [comment]
Hi @yibenhuang 

Does `python -m black` work? That's what nbqa calls. If it doesn't, then you might be able to get around it by using [--nbqa-shell](https://nbqa.readthedocs.io/en/latest/configuration.html#shell-commands)

**Comment by yibenhuang** [comment]
Hi @MarcoGorelli ,

As the virtual environments don't have the tools (eg: `black`) installed, `python -m black` didn't work. But with `--nbqa-shell` in the command line, it **worked** :> 

> `--nbqa-shell`:  run `command` directly rather than `python -m command`

To better understand, as instructed above, my understanding is that `nbqa` runs the `black` command which comes from pipx (which is globally installed), rather than calling that module in a virtual environment (which does not have `black` installed), such that it works. Am I right?

**Comment by MarcoGorelli** [comment]
yeah it'll just call whatever `black` points to

**Comment by yibenhuang** [comment]
Good to know, and thanks for this awesome tool!
