### ISSUE TITLE
Bug with isort --float-to-top when the first cell is markdown

### ISSUE THREAD

**Issue by tqa236** [nbQA-dev/nbQA#766]
Hello, thanks a lot for this awesome tool. I'm able to use it with a lot of libraries, but I run into a small problem with `isort`

## Problem

I have a simple Jupyter notebook as below (first cell is a markdown)

![image](https://user-images.githubusercontent.com/25203655/196887571-a645f33b-4e57-4769-9578-dcae4c03e303.png)

When using `nbqa-diff`, the diff looks correct

```bash
❯ python -m nbqa isort --float-to-top "notebook/Test.ipynb" --nbqa-diff
Cell 1
------
--- notebook/Test.ipynb
+++ notebook/Test.ipynb
@@ -1 +1,2 @@
+import time

Cell 2
------
--- notebook/Test.ipynb
+++ notebook/Test.ipynb
@@ -1 +1 @@
-import time
+
```

When applying the change, it's no longer correct (all imports are removed)

```bash
> python -m nbqa isort --float-to-top "notebook/Test.ipynb"
> git diff
diff --git a/notebook/Test.ipynb b/notebook/Test.ipynb
index fd0d300..feb9898 100644
--- a/notebook/Test.ipynb
+++ b/notebook/Test.ipynb
@@ -8,25 +8,13 @@
     "Markdown"
    ]
   },
-  {
-   "cell_type": "code",
-   "execution_count": null,
-   "id": "8b3f984a-826b-443e-bacf-bbed12c07bd2",
-   "metadata": {},
-   "outputs": [],
-   "source": [
-    "import os"
-   ]
-  },
   {
    "cell_type": "code",
    "execution_count": null,
    "id": "50731a1b-213b-4485-91bf-2d80fb522371",
    "metadata": {},
    "outputs": [],
-   "source": [
-    "import time"
-   ]
+   "source": []
   }
  ],
  "metadata": {
```

## Version

OS: Ubuntu 22.04 on WSL (Windows 11)

Python 3.10.6

```
nbqa==1.5.2
isort==5.10.1
```

Is this a bug or do I use `nbqa` incorrectly? If it is a bug, can you fix it, please? Thank you very much.

**Comment by MarcoGorelli** [comment]
Probably a bug - thanks for the report! I'll take a look

**Comment by MarcoGorelli** [comment]
@all-contributors please add @tqa236 for bugs

**Comment by MarcoGorelli** [comment]
@tqa236 this should be fixed in version 1.5.3 - if you could try and let me know if it doesn't work, that'd be much appreciated 🙏 

And thanks for your excellent bug report with an easy-to-reproduce example!

**Comment by mdeboc** [comment]
@MarcoGorelli you're fast!

**Comment by tqa236** [comment]
@MarcoGorelli It works perfectly. Thanks a lot!
