### ISSUE TITLE
Support for Ruff

### ISSUE THREAD

**Issue by marscher** [nbQA-dev/nbQA#772]
Ruff is an uprising super fast Python linter written in Rust. It seems like one needs to add some tests and docs for it, since it runs out of the box.

```
pip install ruff
nbqa ruff /my_project/notebook_dir
```
output:
```
Found 47 error(s).
/home/marscher/sources/weldx/tutorials/01_01_introduction.ipynb:cell_2:1:1: E402 Module level import not at top of file
...
```
Also the fix option works, since this project is very cleverly designed!

**Comment by MarcoGorelli** [comment]
Thanks @marscher !

Yeah we should definitely add tested support for `ruff` and a `nbqa-ruff` hook - are you interested in contributing a pull request?
