### ISSUE TITLE
Cell ids change on each pre-commit run

### ISSUE THREAD

**Issue by joshdunnlime** [nbQA-dev/nbQA#778]
When running the `pre-commit --all-file` with version:
> "nbformat": 4,
> "nbformat_minor": 5

It changes the cell id even when nothing else changes in the ipynb file. As you might imagine, this make VC with git near impossible. Any way around this? Thanks.

**Comment by MarcoGorelli** [comment]
hi @joshdunnlime - do you have an example please?

`pre-commit --all-file` isn't a valid command, please show exactly what you ran
