### ISSUE TITLE
implicitly imported members (e.g. display) reported as missing

### ISSUE THREAD

**Issue by marscher** [nbQA-dev/nbQA#785]
For instance a cell containing:

```python
display(obj)
```
will report: F821 Undefined name `display`

for tools like Ruff and Flake8.

I wonder how I can workaround this or if we even need to consider to transform the code to include implicit imports by the notebook?

**Comment by MarcoGorelli** [comment]
hi @marscher , thanks for your report

you can import it explicitly:
```
from IPython.display  import display
```

**Comment by marscher** [comment]
Indeed. That was too simple. Sorry for wasting your time.
