### ISSUE TITLE
Error when importing nbqa.find_root in v1.6.1 

### ISSUE THREAD

**Issue by DManowitz** [nbQA-dev/nbQA#790]
With version 1.6.1 of nbqa, when importing nbqa.find_root, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\nbqa\find_root.py", line 26, in <module>
    ) -> Path:
  File "C:\Users\manow\miniconda3\envs\py37_ml_TfGpuMain\lib\functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

Looking through the history of this file, it appears that leaving off the parentheses from the `@lru_cache` decorator for `find_project_root` is likely the cause of this error.

**Comment by MarcoGorelli** [comment]
hi @DManowitz - are you using python3.7? python3.8 is the minimum version required

**Comment by DManowitz** [comment]
Then someone needs to at least update conda b/c it shows python >=3.7.0 there.

**Comment by MarcoGorelli** [comment]
ok it's 3.8.0 here:

https://github.com/nbQA-dev/nbQA/blob/220dacf44e6cc234b8ef87863a31ff9d46dad920/setup.cfg#L35

please report to conda then, thanks!

**Comment by MarcoGorelli** [comment]
Should be fixed now (I guess I need to cut a new release for it to take effect? I've removed conda from the readme anyway)
