### ISSUE TITLE
False positive for `ruff` `I001` (isort)

### ISSUE THREAD

**Issue by felix-cw** [nbQA-dev/nbQA#796]
The issue arises when running `nbqa ruff`

- on a notebook with both standard library and third party imports in the first cell
- where the isort checks are enabled e.g. with `--select=I`

In this case, there seems to always be a false positive error message of

```
I001 [*] Import block is un-sorted or un-formatted
```

The `--fix` option does not change the notebook, but reports it as fixed anyway

```
Found 1 error (1 fixed, 0 remaining).
```

I use a notebook with the following two cells

```python
import os

import numpy as np
```

```python
cwd = os.getcwd()
x = np.arange(1, 10)
```

My versions:
python 3.9.15
nbqa 1.6.1
ruff 0.0.247

**Comment by MarcoGorelli** [comment]
thanks @felix-cw for the report, fix incoming

**Comment by MarcoGorelli** [comment]
@all-contributors please add @felix-cw for bugs
