### ISSUE TITLE
adding python bytes to all contributors

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#816]
looks like one of the keys is for "Podcasts, background music or sound effects", so let's recognise them (this project kinda took off when they kindly covered it in an episode 2 years ago)

**Comment by MarcoGorelli** [comment]
@all-contributors please add okken for audio

**Comment by MarcoGorelli** [comment]
@all-contributors please add @mikeckennedy for audio

**Comment by MarcoGorelli** [comment]
https://github.com/all-contributors please add @mikeckennedy for audio

**Comment by MarcoGorelli** [comment]
@all-contributors please add @mikeckennedy for audio

**Comment by mikeckennedy** [comment]
Thank you all ( @MarcoGorelli ). Really appreciate this.
