### ISSUE TITLE
Add support for ruff as pre-commit-hook

### ISSUE THREAD

**Issue by havspect** [nbQA-dev/nbQA#822]
I think the title speaks for itself. Ruff offers a pre-commit-hook which can easily be used with nbQA. 

I would love to help with this issue.

**Comment by MarcoGorelli** [comment]
isn't it there already?

**Comment by MarcoGorelli** [comment]
yup: https://github.com/nbQA-dev/nbQA/blob/3e48f1d425d7abb195b5ff5cb02df39b70eceb3c/.pre-commit-hooks.yaml#L89-L96
