### ISSUE TITLE
`nbqa-ruff` uses outdated JSON schema

### ISSUE THREAD

**Issue by janosh** [nbQA-dev/nbQA#824]
```sh
$ pre-commit run --all-files
nbqa-ruff................................................................Failed
- hook id: nbqa-ruff
- exit code: 2

~/.cache/pre-commit/repo7oua9kz1/py_env-python3.11/lib/python3.11/site-packages/autopep8.py:182: DeprecationWarning: lib2to3 package is deprecated and may not be able to parse Python 3.10+
  from lib2to3.pgen2 import tokenize as lib2to3_tokenize
error: TOML parse error at line 58, column 5
   |
58 |     "FLY", # flynt
   |     ^^^^^
Unknown rule selector: `FLY`
```

Related: https://github.com/astral-sh/ruff/issues/4529

Probably just needs a version bump.

**Comment by MarcoGorelli** [comment]
hey @janosh 

yeah `ruff` isn't pinned by nbqa, you should be able to pin it by setting it in `additional_dependencies`, like `additional_dependencies: [ruff==0.0.272]`

**Comment by janosh** [comment]
I'm confused. Without pin, how come it doesn't default to the latest version?

**Comment by MarcoGorelli** [comment]
I guess because you installed it some time ago, before the latest release was out, and `pre-commit` cached that `ruff` version
