### ISSUE TITLE
Support for ruff format

### ISSUE THREAD

**Issue by jpmckinney** [nbQA-dev/nbQA#833]
As a fast, equivalent alternative to black: https://astral.sh/blog/the-ruff-formatter

As far as I can tell, I cann't use nbqa to run both the ruff linter (`$ ruff`) and the ruff formatter (`$ ruff format`) (I can maybe use `addopts` to run the formatter instead of the linter – but, in any case, I can't get both to run).

**Comment by MarcoGorelli** [comment]
hey - doesn't ruff support notebooks now?

**Comment by jpmckinney** [comment]
Ah, yes, looks like it: https://docs.astral.sh/ruff/faq/#does-ruff-support-jupyter-notebooks

**Comment by MarcoGorelli** [comment]
cool - closing then, might archive this project then, was fun whilst it lasted 😄

**Comment by jpmckinney** [comment]
FWIW, `ruff format` makes other changes to the ipynb file (changing indentation, reordering JSON members, etc.). It doesn't just format the Python code.

I also extend nbqa with custom hooks.

So, it remains independently useful!
