### ISSUE TITLE
tests/tools/test_ruff_works.py fails as ruff <path> was deprecated in ruff 0.3.0

### ISSUE THREAD

**Issue by funkeleinhorn** [nbQA-dev/nbQA#837]
[ruff 0.3.0](https://github.com/astral-sh/ruff/releases/tag/v0.3.0) deprecated `ruff <path>` in favor of `ruff check <path>`. See [this PR](https://github.com/astral-sh/ruff/pull/10169) for more info. Because [tests/tools/test_ruff_works.py](https://github.com/nbQA-dev/nbQA/blob/main/tests/tools/test_ruff_works.py#L48) uses `ruff <path>` the test now fails. The test should be updated to use `ruff check <path>`.

**Comment by MarcoGorelli** [comment]
thanks - want to make a pr?

**Comment by funkeleinhorn** [comment]
Found the time to look into it and created a PR.
