### ISSUE TITLE
Version >= 1.8.0 breaks nbqa 'ruff format' shell command

### ISSUE THREAD

**Issue by fvonbergen** [nbQA-dev/nbQA#843]
The following commit [2303a49df1a15d73fdbd525f41e37c3b3f82fcf8](https://github.com/nbQA-dev/nbQA/commit/2303a49df1a15d73fdbd525f41e37c3b3f82fcf8) breaks ruff nbqa usage of the form:
```
nbqa 'ruff format' .
```

Besides the `main_command` we could also analyze the `subcommands` list.

```
    if main_command == "ruff":
        subcommand = subcommands if len(subcommands) == 1 and subcommands[0] in ["check", "format"] else "check"
        sub_commands.insert(0, subcommand)
```

**Comment by MarcoGorelli** [comment]
thanks @fvonbergen for the report! fix incoming
