### ISSUE TITLE
CLN split __main__.py into smaller modules

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#95]

**Comment by girip11** [comment]
As part of this effort, I have raised this PR https://github.com/girip11/nbQA/blob/simple_config_refactoring/nbqa/config.py to separate configuration code out of `__main__.py`

**Comment by s-weigand** [comment]
IMHO the `__main__.py` should only import a function and run it in `if __name__ == "__main__":`.
For me, the only legitimate reason to have definitions in `__main__.py`, is if it is the only module, besides `__init__.py` (which is the way `nbqa` started out at its birth, I guess).

As a side note, `__main__` also isn't picked up as a module, by `autodoc`.

**Comment by MarcoGorelli** [comment]
this is arguably done by many of Girish's excellent refactoring PRs
